<h1>How was the Ramakrishna Movement started?</h1>
<h2>&nbsp;</h2>
<p>The Ramakrishna-Vivekananda Vedanta Movement has its origin in, and draws its inspiration from, the life of the great Hindu saint and seer, Sri Ramakrishna, whose name it is associated with. Born of devout Brahmin parents in an idyllic village of Bengal in the year 1836, he had ecstatic experiences in boyhood, which intensified his inborn love of God. At the age of seventeen he went to Calcutta to live with his brother, who conducted a Sanskrit academy. There he occupied himself mostly with religious duties. Though possessed of extraordinary memory, keen intellect, and artistic aptitudes, he refused to acquire secular knowledge. His brother tried in vain to give him a Sanskrit education, but his heart yearned for the spiritual enlightenment that would remove all darkness forever.</p>
<h3>Monks with a Mission</h3>
<p>Three years later he was appointed priest for the worship of Kali, the Divine Mother of the universe, in a newly founded temple situated on the Ganges at Dakshineswar four miles north of Calcutta. As soon as he began worshipping the Divine Mother in the image installed in the temple, an all-consuming longing for her vision grew within him. He was unable to think even of food or rest. Sleep forsook him. No longer could he perform the prescribed rituals of worshipping the deity. In the intense hunger of his soul, he practiced hard disciplines, prayed to the Divine Mother day and night, intently meditated on Her, poured out his devotion at Her feet in song, and cried bitterly like a child to see Her. At last one day he entered into a state of beatitude in which She revealed Herself to him. Yet he could not rest satisfied. His heart craved a continuous vision of Her. He prayed more and more and before long was able to see Her not only in ecstasy but in the normal state of consciousness, with open eyes.</p>
<p>He was in constant divine inebriation, yet even so he yearned for the realization of God in different aspects and forms. With superhuman energy, ardour, and devotion he practiced, one after another, various spiritual disciplines prevalent in Hinduism - from the intricate ritualism of the Tantras to the abstruse meditation of Yoga, from the ecstatic devotional practices of Vaisnavism to the transcendental Self-realization of nondualistic Vedanta - and he attained the Supreme Being through each of them. Afterward he turned to Islam, with the same result; and later in life, to Christianity. In regard to the latter, he had a vision of Jesus Christ and was convinced of His Divine Sonship.</p>
<p>His tremendous struggle for God-realization extended over twelve years. During this period and the remaining eighteen years of his life he had varied mystical experiences and realizations repeatedly. He saw myriads of spiritual visions, and dwelt in sublime ecstatic moods. In his spiritual practices he was guided by adepts, who came to him at the hour of need, directed as it were by the Divine Will.</p>
<p>He attained to the pinnacle of spiritual realization - the transcendental experience of Nirguna Brahman, the One without a second, free from all distinctions. Once he stayed in that state continuously for six months. Indeed, so accustomed did he become to its sublime height that the natural tendency of his mind was to soar beyond time and space, name and form to the Limitless One. However, at the Divine Call, he gradually trained his mind to occupy a unique position in the spiritual realm. His mind usually stayed on the borderline of the Absolute and the relative, so that it could turn to either at any time. As a result, in the normal state of consciousness he always perceived the One in the many and the many in the One, and he was able to shift from the manifold experience to the Unitary Consciousness with ease.</p>
<p>Though the aspirant is very rare who can right practice even a single spiritual method and reach the goal after lifelong struggle, yet it was the genius of Sri Ramakrishna to finish the whole course of the world's spiritual lessons, so to speak, within a few years. Thus he demonstrated the truth that the Goal is the same, though the paths vary, that the Divine Being is both transcendental and immanent, and that It has many aspects and forms. In dealing with people he always looked upon them as Narayanas, he veritable manifestations of God.</p>
<p>It was revealed to Sri Ramakrishna by his spiritual experiences that he had a Divine Mission to fulfill; that his practices and realizations were intended not for his personal benefit but for the good of humanity. He was to establish a new religious order for the regeneration of India, for the spiritual awakening of mankind, and for the establishment of harmony among the different religions of the world. He foresaw that earnest seekers of various sects, communities, and ranks of society would come to him for solace, inspiration, guidance, and enlightenment. During the last twelve years of his life just such a stream of people constantly flowed into him room. He also had the vision that his message would spread far beyond the seas among devotees who spoke a language which he himself did not know.</p>
<p>Sri Ramakrishna had visions of his intimate disciples and devotees, lay and monastic, even before they came to him. Some of them, he knew, would be young - they were the potential monks especially chosen by the Divine Mother to carry our Her mission. They arrived one by one during the last six years of his life (1881-1886) - most of them were indeed very young - and he recognized each of them at first sight. It was during his last illness in 1886 that the entire band of his intimate disciples rallied around him. The would-be monks altogether numbered sixteen.</p>
<p>Twelve of them, who constantly attended on him, organized themselves under the leadership of Narendranath (afterward Swami Vivekananda) and served the Master with utmost care, love, and veneration. Their whole-hearted love of God and devotion to the Master and his ideals led to the formation of the brotherhood, which soon after his death was to develop into the Ramakrishna Order.</p>
<p>The Master himself took decisive steps to lay its foundation. He often exhorted the young disciples to follow the path of renunciation for the realization of God and for the service of God in man. On a certain occasion, charging Narendranath not to let his ideas die out after his death, he said to him, "I leave these boys in your charge. See that they dedicate themselves to the Divine Mission and do not enter into the world." As preparatory to monastic life he once asked the young disciples to beg their food from door to door, regardless of caste. A few days later he gave each of them a piece of ochre cloth, the emblem of the life of renunciation. Shortly before his passing away on August 16, 1886, he transmitted his powers to Narendranath, saying to him, "By virtue of this gift you will do immense good to the world, and not until then will you gain release."</p>
<p><strong>Swami Satprakashananda</strong> <i>Swami Vivekananda's Contribution to the Present Age The Vedanta Society of St. Louis; 1978</i></p>
