<h1>Universal Temple at Nagpur</h1>
<h2>&nbsp;</h2>
<h3>Universal Temple of Sri Ramakrishna at Ramakrishna Math - Nagpur</h3>
<p><strong>This article has been written by Shri G.V. Reddy, the Architect of The Universal Temple at Nagpur</strong></p>
<ul>
	<li>Nagpur in History</li>
	<li>Ramakrishna Math in Nagpur</li>
	<li>Temple Worship - Evolution</li>
	<li>Principles behind The Temples of Sri Ramakrishna</li>
	<li>Layout of the Nagpur Math and Location of Temple</li>
	<li>Temple: Design concept and aspirations</li>
	<li>Architectural treatment of the Temple's Exterior</li>
	<li>Conclusion</li>
</ul>
<h3>Nagpur in History</h3>
<p>Nagpur is the most important city in the Vidharbha region of Maharashtra State. Sixteen centuries ago was known as "NAGAPURA" and in 4th Century A.D., this town was located within Nandivardhana district of Vakataka kingdom, which was ruled by Rudrasena II [who married Prabhavati, the daughter of the head of the Gupta Empire Chandra Gupta II (Deva Gupta)]. This queen issued a charter from the feet of the God - Ramagirisevamin, identified with deity at Ramagiri - (modern Ramtek near Nagpur). This holy temple town Ramagiri is also immortalized by Kalidasa in his Megaduta. By the end of 5th century A.D. Nagpur district formed part of an independent kingdom known as Vatsagulma (modern Wasim). In the 13th century, the city Srivardhana (near modern Nagpur) was a part of the kingdom of Yadavas, who ruled from Devagiri (modern Daulatabad). The fortified part of central Nagpur contains many palaces, Royal tombs, ancient temples and the mansions (wadas) of the nobles of the Bhosale Kings, who, under the suzerainty of the Maratha Empire ruled over the Vidharbha region from Nagpur as their capital. Till the Bombay state was formed in the year 1956, Nagpur was the capital of Central Provinces. Lying almost in the center of the North-south axis of India, today Nagpur is not only the second capital of Maharashtra state but also it is an important commercial and educational center in Central India catering to the needs of the northern region of Maharashtra and southern part of Madhya Pradesh.</p>
<h3>Ramakrishna Math in Nagpur</h3>
<p>Srimat Swami Shivanandaji Maharaj, the second President of the Ramakrishna Order during his first visit to Nagpur in the month of February 1925, sowed the seed for starting a center of the Ramakrishna Order. This seed had sprouted with the donation of a big plot of land in Dhantoli (Craddock town) and also with the beginning of worship of Sri Ramakrishna in a humble hut built on this land with clay walls.</p>
<p>Impressed with the enthusiasm and devotion of the local devotees, exactly after two years (February 1927) Swami Shivanandaji again visited Nagpur and at his insistence was accommodated in a tent specially erected by the side of the hut housing the shrine of Sri Ramakrishna. During his weeklong stay, he laid the corner stone of the prospective Ashrama, after offering worship to Guru Maharaj.</p>
<p>On this auspicious occasion he meditated and in high state of consciousness while looking at the land with wild growth of vegetation, he exclaimed "Jangal me mangal ho jayega" (This forest will be endowed with holiness).</p>
<p>While uttering these prophetic words, Mahapurushji was also aware that the task be fulfilled only when it is entrusted to a competent person. He found this person in his disciple Swami Bhaskareshwarananda who took over Nagpur Ashram in the month of September 1928 with Rs. two given by his Guru as initial capital to begin his work.</p>
<p>The hut, which then existed in the ashrama site, served as a temple, a dispensary, and also his living space. Towards the end of the year 1929, he could start the construction of the main building of the Ashrama and it was ready for use in the year 1932. This new building initially housed the shrine for the worship of Sri Ramakrishna, a public library, a dispensary and all other appurtenant uses of the ashram.</p>
<p>Due to untiring efforts and leadership of Swami Bhaskareshwaranandaji, this Ashrama had grown with increased activities, which have corresponded with the steady growth of the city of Nagpur and also the claim on ecclesiastic services of the Ashrama by the devotees of Vidharbha region.</p>
<p>Before he departed from this world in the month of January 1976, Swami Bhaskareshwaranandaji, as the head of the math could carry on all the service activities like medical help for the poor, maintenance of a library, a home for poor students, the publication of Marathi and Hindi books on Vedanta, and on the Holy Trinity, and the sale of publications on Ramakrishna, Holy Mother Sarada Devi, and Swami Vivekananda and also on Vedanta in separate buildings with adequate accommodation. Only the shrine for the worship of Sri Ramakrishna as it was set up in the year 1932 in a small room in the eastern end of the ashrama remained untouched. By no stretch of imagination it can be said that this existing shrine can satisfy even the partial needs of the large number of devotees who participate in the daily worship of Sri Ramakrishna. Therefore, the dire need of Nagpur Ramakrishna Math is a temple of Sri Ramakrishna with adequate space and facilities.</p>
<h3>Temple Worship - Evolution</h3>
<p>There is no evidence of worship in the conventional temples by the people belonging to Vedic age. The priest class worshipped in groups sitting around a fire altar. The laity resorted to congregational worship of the natural elements in the manner of experiencing their gratitude or for providing protection from the ravages of nature. Many races and class in this world were used to congregational worship only. Early Buddhists used to gather around a Bhiksha seated under the shade of large trees and heard the sermons of the life and teachings of Buddha, and they also worshipped the symbols representing Buddha placed at the foot of the tree which was called "Vruksha Chaitaya". Later they resorted to congregational worship in chaityas consisting of long rectangular halls with apsidal ends containing a symbol of Buddha, which were usually in the shape of native Stupa.</p>
<p>The worship of the image of Buddha began only with the advent of Mahayana Buddhism in 2nd century A.D. A simple Hindu temple built according to agamic codes and Vastu texts, would consist of cell (Garbhagruha) sheltering the image of the deity and a front vestibule, which is called "antarala" or ardhamandapa. A fully developed Hindu temple, in addition to Grabhagruha and Antarala would also have a mahamandapa (prayer hall) and a "Mukhamandapa" (entrance portico). These conventional Hindu temples as they are known today began appearing when people resorted to the worship of personal gods, which corresponds to Puranic period of Indian religious history. With the introduction of Agamas which codified the system of worship of various forms of gods and goddesses, in all parts of India, it is possible to witness a basic unity in the pattern of the plan of the temple, though the super structures are adorned with diverse architectural forms and styles.</p>
<h3>Principles Behind The Temples of Sri Ramakrishna</h3>
<p>Numerous religions including Hindusim, Islam, and Christianity are practiced in India, although, Hindus constitute the majority of the people of India. But various religions must have mutual understanding. Sri Ramakrishna brought this harmony of religions. That is why, in the modern age, he is a special ideal to be emulated. For these reasons a Ramakrishna temple in the midst of many other temples places of worship is relevant and a necessity for the people.</p>
<p>During his lifetime Sri Ramakrishna never did anything to introduce any cult. However, he prophesied that in future he will be worshipped as an ideal wherever this message spreads among the people. Swami Vivekananda also desired the worship of Sri Ramakrishna more as a principle than as a person. He saw Sri Ramakrishna as the embodiment of all religions. According to Swamiji this harmony of religions is the one important message Sri Ramakrishna left for the world.</p>
<p>The following words of Swamiji reveal his mental picture about the temple of his Gurudev:</p>
<p>"… In the building of this prospective temple, I have the desire to bring all that is best in the European and Western art. I shall try to apply in its construction all the ideas about architecture, which I have gathered in my travels all over the world. A big prayer hall will be built, supported on numerous clustered pillars. On its walls hundreds of lotuses will be in full bloom. It must be big enough to accommodate a thousand persons sitting in meditation. Within the temple there would be a figure of Sri Ramakrishna seated on a swan. On the two sides of the door will be represented by the figure of a lion and a lamb licking each other's body in love - expressing the idea that great power and gentleness have become united in love. I have these ideas in mind and if I live long enough I shall carry them out."</p>
<p>The architectural forms with embodiments as elucidated by Swamiji also disclose that in the formulation of the design of the temple of Sri Ramakrishna none of the rigid codes of Agamas and vastu shastras are to be observed. He stressed that the temple as a whole should help spiritual growth of the worshippers, which, in brief, is the basic philosophy for guiding the formulation of the design of the temple of Sri Ramakrishna.</p>
<p>Though we got the design of the temple he proposed for his Gurudev, worked out by his gurubhai Swami Vijnanananda, he could not get it built during his lifetime. However, when he departed from this world, he entrusted this holy task to Swami Vijnanananda who was a qualified civil engineer. 35 years later the corner-stone was laid by Swami Shivananda in his capacity as the second President of Ramakrishna Order. Under the guidance of Swami Vijnanananda the construction work was started in the year 1935 and as the fourth President of the Ramakrishna order he consecrated the temple by the end of the year 1937. On this occasion, Swami Vijnanananda expressed his satisfaction for having fulfilled the command he received from Swamiji.</p>
<p>This grand cathedral of the Ramakrishna Order is in fact "Symphony in Architecture", and it has become a model and main source of inspiration for shaping the design of the temples of Sri Ramakrishna subsequently in many places in India and abroad. In obedience to the sublime dictum of Sri Ramakrishna order, "Atmano Mokshartham, Jagaddhitaya Cha", the devotee is expected to meditate and participate in the worship of Sri Ramakrishna, not only for his own emancipation but also for the good of the world.</p>
<p>The principles governing the building of Sri Ramakrishna temples and the system of worship, which should prevail in them, are to be according to the following traditions left behind by Swami Vivekananda and his fellow disciples (gurubhais).</p>
<ul>
	<li>Irrespective of cast, creed or religion and nationality, every one wearing clean dress can enter the temple and participate in the worship. Entry into the temple with footwear is prohibited.</li>
	<li>The entrance portico, which is comparable to the Mukhamandapa of a traditional Hindu temple, should be provided with the facilities for the devotees for keeping their feet clean before entering the prayer hall.</li>
	<li>The prayer hall (Natmandira), which is comparable to the Mahamandapa of a traditional Hindu temple, shall be well lighted and ventilated in order to provide tranquillity and necessary comforts to the devotees who will be seated in it for meditation and prayer. The devotees in the prayer hall should also have a sense of active participation in the worship with rituals being performed in the shrine, which may contain a picture or image of Sri Ramakrishna.</li>
	<li>The shrine (Garbhamandira) shall be large enough for providing a clear view of the image or picture of Sri Ramakrishna. For this purpose, it may not be separated from the prayer hall by a vestibule (antarala of a traditional Hindu temple.)</li>
	<li>A room for preparing the items for the performance of puja with various rituals should be placed either on one of the sides or in the rear of the shrine (Garbhamandira).</li>
	<li>A room with good light and ventilation is to be set apart as the "Sayana room" of Sri Ramakrishna. It may be attached to one of the sides or the rear wall of the Garbhamandira.</li>
	<li>The Parikrama (circumambulation) path should be provided either around the shrine or the temple.</li>
	<li>For the supply of adequate quantity of fresh flowers for daily worship in the temple, a garden should be developed in the near vicinity of the temple.</li>
</ul>
<p>While preparing the design of the prospective temple of Sri Ramakrishna in Nagpur Math premises, care had been taken to incorporate all the above said distinct features of the temple of Ramakrishna order.</p>
<h3>Layout of the Nagpur Math and Location of Temple</h3>
<p>The area of land at the disposal of the Math is about 2.3 acres and it is divided almost in two equal parts by the main road linking Wardha road with Ajni railway station. Roads on all four of its sides surround the northern half of the land. It houses the oldest main building of the Math, which almost occupies the central part of the site. Its ground floor has verandahs on all four sides shading two rooms and a central hall. The eastern end room is being used as the shrine of Sri Ramakrishna for over seventy years. Due to lack of space, the central hall, which cannot accommodate more than thirty persons, is being used as the prayer hall. The three rooms in the first floor of this building with tiled roofs are being used as the living quarters of the monks of the Math. The access to this main building is through an open court, which extends right up to the northern boundary of the site. This open court is large enough to accommodate a congregation of nearly three thousand devotees on special occasions. Therefore, the Math cannot afford to sacrifice this valuable open space for any other purpose.</p>
<p>The kitchen and dining hall is located in the southeast corner of this part of the site where the activities of the Math was started in 1928 in a small-tiled hut with mud walls. Facing the main road to Ajni Railway station, the monastic workers quarters occupies the southwest corner with a garden strip along the western boundary of this northern plot. The building with two floors at the northwest corner has the student's home in the ground floor and a lecture hall in the upper floor. The office of the Math, the bookshop etc. are accommodated in the building with two floors placed in the north-east corner of the plot.</p>
<p>The southern half of the Math land which gains its access from the main road to Ajni Railway station contains the Library building, Physiotherapy Block, the garages for the vehicles used for mobile medical services and a large building accommodating the book publication department with godowns etc. The open spaces now available in both of the pieces of land owned by the Math are not adequate or suitable for location of any new structure of the magnitude of a temple which should accommodate at least 500 persons in its prayer hall. Therefore, it had become necessary to sacrifice any one of the existing structures for giving place to the proposed temple of Sri Ramakrishna.</p>
<p>The central building which is now being used for the worship of Sri Ramakrishna is the first one to be built. In order to find a suitable home for Sri Ramakrishna who was being worshipped in a small mud hut, this building was undertaken and with meager resources at disposal, it was completed in a hurry. This building, which is over seven decades old, has outlived its life. Any expenditure on remodeling this building with necessary additions and alterations may not be beneficial in the long run. Therefore, without encroaching on the available open spaces, the proposed temple of Sri Ramakrishna will be placed in the space gained by removing this oldest building of the Math.</p>
<p>However, in order to honour the sentiments of the devotees, especially the elders who are associated with the activities of the Math for a long time, care had been taken to place the Garbhamandira of the proposed temple exactly over the very spot where the shrine of Sri Ramakrishna is now existing. In order to avoid the noise and disturbance of the heavy traffic on the main - Ajni Railway station road, and also for ensuring calm atmosphere in and around the temple, it is oriented facing west with its main access from the existing minor road which abuts the western orientation only.</p>
<h3>Temple: Design concept and aspirations</h3>
<ol>
	<li>Ground floor of the Temple
		<ol>
			<li>For the purpose of spreading the message of the Holy Trinity, every Math and Mission Center is in need of a lecture hall. This hall is also to be used for conducting periodical spiritual retreats. The Math Center, which caters to the needs of a large city like Nagpur, requires an auditorium for accommodating at least 500 persons. The land at the disposal of the Math would not permit a separate building for this purpose. Therefore, it was decided to have this essential appurtenant need of the Math in the ground floor of this temple building by raising the prayer-hall floor level by 10' 0" from ground level. The lecture hall in the ground floor, which would mean 62' 0" x 52' 0" can comfortably accommodate 500 persons seated in chairs.</li>
			<li>The space below the garden mandira of the temple will be the stage of the auditorium with spaces set apart for all appurtenant uses. In memory of the founder of Ramakrishna Math at Nagpur, this lecture hall would be named after Swami Bhaskareshwaranandaji.</li>
			<li>The space in the ground floor right below the front portico (mukhamandapa) of the temple and also the front part of parikrama, is to be used for storing at least one thousand pairs of footwear in the built-in racks. After deporting their footware, it will be possible for the devotees to proceed either to the prayer hall on the first floor or to the lecture hall on the ground floor.</li>
			<li>The staircase in the rear of the stage is intended for the exclusive use of the monastic workers who will be in charge of the worship in the garbhamandira and also for the maintenance of the open terrace over the prayer hall and the upper parts of the building consisting of domes, vimanas and the vaulted part of the roof over the prayer hall.</li>
		</ol>
	</li>
	<li>First Floor (Prayer Hall)
		<ol>
			<li>a. Access to the Temple Floor: The floor level of the prayer hall of the temple will be ten feet above the existing ground level of the site. The grand, central stairway flanked by artistic lamp pedestals, provides the main access to the prayer hall through a mukhamandapa like portico. It is also possible to gain access to the prayer hall through the two open staircases placed in the center of the Northern and Southern sides of the prayer hall. The old and physically handicapped devotees can reach the prayer hall through a 4 feet wide ramp provided on the northern side.</li>
			<li>Front Portico (Mukhamandapam): The west facing front portico measures 9'. 0" x 14'. 0" and the architectural treatment of the decorative cusped arch in its front façade and the conical ornamental dome on its roof closely follows the treatment of similar features which are found in the existing ancient temples and palaces in Nagpur city and its vicinity. Care has been taken to formulate the features of the side entrance lobbies of the prayer hall in such a manner that they are in harmony with that of the front entrance portico.</li>
			<li>Prayer Hall (Natamandira) : In the prayer hall with marble flooring, the devotees will remain seated either in meditation or participating in the worship of Sri Ramakrishna, which will take place in the garbhamandira. For providing adequate lighting and ventilation, the sides of the prayer hall would have in all twelve doors opening on to the verandahs which are to be used as Parikrama also. These side verandahs will not only help the reduction of the intensity of heat during summer, but also during winter, would warm up the interior of the prayer hall which measures 40'.0" x 68'.0". For flushing out the hot air which will be accumulated in the vaulted part of the roof over the nave of the prayer hall, twelve decorated ventilations are provided in middle part. Over 400 devotees can be comfortably seated on the floor of the prayer hall. All of them will be able to have the clear view of the white marble image of Sri Ramakrishna to be installed within garbhamandira. For this purpose, care has been taken to avoid any intermediary column within the prayer hall, and the garbhamandira would have a 16'.0" wide door opening fitted with 16'.0" x 10'.0" sliding and folding shutters. These shutters will be closed only during the offering of a food items "naivedya" as part of the rituals in the Garbhagruha.
				<p>The architectural treatment of the natamandira (prayer hall) of Belur Muth temple and also the interiors of rock cut Buddhist Chaityas at Ajanta and Karla are the main sources for determining the decoration of the interior of the prayer hall of this temple which will have a flat roof over its aisles and the vaulted roof with a pointed arch for its nave. The treatment of the roof of this kind is a common feature found in almost all Gothic churches of Europe. On the whole the aesthetically designed and decorated prayer hall of this proposed temple at Nagpur will present an impressive and sublime view from the threshold of its main entrance door.</p>
			</li>
			<li>Garbhamandira: As in the case of any Hindu temple, the heart of this temple of Sri Ramakrishna is its Garbhamandira which measures 18'.6" x 18'.6'. The white marble image of Sri Ramakrishna seated on a fully bloomed lotus base, will be installed over a marble pedestal with suitable embellishments. The height of the marble image is 4'.6" and the total height including the pedestal would be 6'.0". This will be located in the center of the rear half of the garbhamandira. For ensuring absolute cleanliness, the floor and the walls of the garbhamandira would be cladded with polished marble slabs. The wide door- opening separating the garbhamandira from the prayer hall when bordered by an architecture filled with wooden carvings will ensure a serene view of the spotlighted image of Sri Ramakrishna. The floor level of the garbhamandira will be one foot higher than that of a prayer hall.</li>
		</ol>
	</li>
</ol>
<h3>Architectural treatment of the Temple's Exterior</h3>
<p>"Nagara Idiom is one of the three basic classical styles of Hindu temple architecture which attained maturity by the end of 10th century A.D. It was evolved and perfected by the master builders who were mostly patronized by the royal families, which ruled over the kingdom in Central India. Nagpur is located in their region and it had been the capital of the Bhosale rulers in the 17th and 18th centuries. Today, in and around Nagpur, including Ramkantak, there are a good number of edifices in the shape of temples, forts, and places which had been built with a distinct style of architecture, and the citizens of the region are proud of their cultural heritage. Therefore, in due regard to the desire of the local devotees, the design of the temple was formulated with the incorporation of the architectural features and forms of the ancient monuments of this region with necessary simplification and modification to suit the temple's overall profile, which is mainly based on the architectural features of Belur Math Temple.</p>
<ol>
	<li><strong>External walls of the Temple:</strong>
		<p>Efforts will be made to clad the plain external surfaces of the walls with Dholpur white stone slabs. For breaking the monotony, red sand stone slabs also many be used, especially in the external surfaces of the ground floor walls. The treatment of the ornamental cornice (Parastara) at the top of all external walls, with 2`.6" wide chajja supported by ornamental brackets, and the parapet above with decorative panels, are all based on the patterns found in Belur Math and the Mahamandapas of the ancient temples within Nagpur city. The embellishments of all the door and window openings of this proposed temple, with ornamental architecture, chajjas and cornices are adopted from the ones found in the ancient palaces and Wadas of Nagpur region.</p>
	</li>
	<li><strong>Front Façade of the Temple</strong>
		<p>For want of space, this proposed temple will be set back from the western boundary of the plot, by about 35`.0" only. The grand central staircase, which gives the main access to prayer hall floor, will be projecting into the front open space by about 20'.0". The special feature of this temple is that the verandah, which is to be used as 'parikrama', girdles all the rooms in the first floor including the prayer hall. The wide openings in between the columns in the exteriors of the mahamandapas of the ancient temples in Nagpur city are treated with the curved arches similar to those found in ancient buildings (temples and palaces) in Rajastan, which had been built during the Muslim rule in Northern India. These highly decorated cusped arches resting on typical fluted and tapering circular columns with decorated square base and caps, are dexterously used for treating the wide openings in the parikrama path (verandas) and also the entrance doorways in all the four facades of the building. The architectural forms of the type of pyramidal or conical tower over the mukhamandapas of most of the ancient temples in Central India, which had been built according to Nagara styles of architecture, have been adopted for the towers over the front and side entrance porticos of this proposed temple.</p>
	</li>
	<li><strong>Sikhara over Garbhamandira</strong>
		<p>The Sikhara over garbhamandira is the most dominating feature of any Hindu temple that is built according to Nagara architectural idiom. The Sikhara of Belur Math temple was based upon the "Navarathna" Shikara of Bhavatarini (Kali) temple at Dhakshineshwar where Sri Ramakrishna spent most part of his life. However the form of the big central dome, placed over the garbhamandira and the eight smaller ones around the big one, which have been placed in two tiers at the four corners of the garbhamandira of Belur Math temple were fashioned after the domes of the cathedrals and churches of Europe (St. Paul's' Cathedral at London and St Peters' Cathedral in Rome) which had been built in 16th and 17th centuries according to renaissance style of Architecture. The features of the central dome crowning the garbhamandira of the proposed temple at Nagpur are similar to the one of Belur Math temple. With this exception, the features of small towers at the four corners of garbhmandira and the three mandapa tower-like features abutting the rear and sides of the square part of the tower over garbhamandira, are respectively based on the 'Latina Shikaras and the Samvarnas (pyramidal roof over the square mandapas) of the Nagara Temples of Vidharbha region. The total height of the tower (shikara) over the Garbhamandira inclusive of the 3`.0" high copper kalasa (finial) over the amalaka crown of the central dome is 67`.0" from the ground level.</p>
	</li>
</ol>
<h3>Conclusion</h3>
<p>This design of the Universal Temple of Sri Ramakrishna incorporates many of the features of the styles of architecture, which are found in the ancient religious edifices in the region around Nagpur. However in shaping the design, enough care has been bestowed to preserve the basic architectural form and profile of the Belur Math Temple, which in fact is the Cathedral of the Ramakrishna Order. The person who designed this temple of Ramakrishna is Sri Venkatramana Reddy - a qualified architect who designed and got involved in the construction of Sri Ramakrishna temples in the Math and Mission centers at Hyderabad, Rajahmundary and Vishakapatnam in Andhra Pradesh and in the Math Centers at Chennai and Madurai in Tamil Nadu. During his lifetime he has also handled several major architectural projects for the Government of Andhra Pradesh and Tirmala Tirupathi Devasthanams. He was actively involved in the renovation of several major temples in Andhra Pradesh including Srisailam, Bhadrachalam, Simhachalam, and Annavaram etc. He had extended his services for designing this temple of Sri Ramakrishna, not in the least as the enumerated professional, but more as a devotee of Sri Ramakrishna. He has also offered his services during the construction of this temple. Depending upon the timely flow of adequate funds it will be possible to complete the building within a period of two years from the date of commencement of work. This imposing Universal Temple of Sri Ramakrishna, embracing the site now occupied by the 70 years old shrine of the Math, when completed, will not only become one of the grand edifices of the city of Nagpur but also fulfill the long cherished desire of the devotees of Sri Ramakrishna at Nagpur and in the Vidharbha region of the Maharashtra State.</p>

