<h1>Why is it called the Ramakrishna-Vivekananda-Vedanta Movement?</h1>
<h2>&nbsp;</h2>
<h3>The Ramakrishna - Vivekananda Movement</h3>
<p>The distinctness of the Ramakrishna-Vivekananda Movement from the traditional Vedanta:</p>
<p>That the real self of man is ever pure, self-luminous, free, is universally true. The present movement declares this truth as central to all religions, although it is more or less explicit in some and in others more or less implicit. By arousing man's faith in himself it can serve as the key to his edification and advancement. The practical application of this truth in modern times by the movement is in some respects an innovation on the traditional methods of Vedanta. The general tendency of classical Vedanta is to impart this knowledge to earnest seekers of Truth and to apply it to their spiritual development particularly. On the other hand, the neo-Vedanta movement aims to teach it to men and women in various levels of life, thereby awakening their faith in themselves and others, so that they can achieve physical, mental, and moral growth individually and collectively with a spiritual outlook on life and proceed toward the Supreme Goal from their present level of development, whatever that may be.</p>
<p>Moreover, traditional Vedanta stresses the need for the secluded life for spiritual aspirants and exhorts them to carry on their own Liberation by self-knowledge. But this Movement enjoins on them a twofold duty: striving after Liberation by solitary practice, and also doing good to the world as a part of spiritual discipline for Self-realization.</p>
<p>There are sharp differences among Vedanta schools, monistic (nondualistic) as well as monotheistic. The monotheistic school includes no less than five distinct systems. The different systems of Vedanta have often been considered contradictory, while the Ramakrishna Order views them as complementary, as so many ways of comprehension, or stages of realization, of Brahman.</p>
<p>A distinct contribution of the Ramakrishna-Vivekananda Vedanta Movement to the modern world is its message that all help given to men by individuals or by society should be based on the recognition of man's innate divinity regardless of man's differences. The only way to mutual regard, love and unity among mankind, on which rest peace and progress in life, is to find an all-embracing ground of human relationship that transcends all distinctions of race, nationality, color, creed, rank, and merit. That this precept can actually be carried into practice has been exemplified by the Movement's various institutions, framed for the service of God in man. The Movement calls on its followers to see God in the needy, the distressed, and the diseased, and to serve them as if one were serving God. Work done in this spirit is veritable worship.</p>
<p><strong>Swami Satprakashananda</strong> <i>Swami Vivekanand Contribution to the Present Age The Vedanta Society of St. Louis; 1978</i></p>
