<h1>What were Holy Mother's teachings on Japa and Meditation?</h1>
<h2>&nbsp;</h2>
<h3>At Udbhodhan 1909</h3>
<p>Pray to the Lord to make your heart as pure as the star. As a result of sincere and regular japa and meditation you will find that the Lord will speak to you. All your desires will be fulfilled and you will experience pure bliss.</p>
<p>Realization of God, or meditation, all these depend on the mind. Concentrate, and everything will come to pass.</p>
<p>Do not give up japa even if the mind is unsteady and unwilling. You must go on with the repetition. And you will find that the mind is getting gradually steadier-like a flame in a windless corner. Any movement in the air disturbs the steady burning of the flame; even so the presence of any thought or desire makes the mind unsteady. The mantra must be correctly repeated. Incorrect utterance delays progress.</p>
<p>One should practice japa and meditation at regular times, giving up idleness. While living a Dakshineswar I used to get up at 3 o'clock in the morning and practice japa and meditation. One day I felt a little indisposed and left the bed rather late. The next day I woke up still late through laziness. Gradually I found that I did not feel inclined to get up early at all. Then I said to myself, "Ah, at last I have fallen a victim to idleness." There upon I began to force myself to get up early.</p>
<p>Gradually I got back my former habit. In such matters one should keep up the practice with unyielding resolution.</p>
<p>One must do some work. Through work alone one can remove the bondage of work, not by avoiding work. Total detachment comes later on. One should not be without work even for a moment.</p>
<p>(To a person who carelessly threw away the broom after sweeping the courtyard) "What is this? You have thrown away the broom with such disrespect when the work is done. It takes only the same length of time to put it gently in a corner as it does to throw it aside. One should not trifle with a thing, though it may be very insignificant. Will you not again need that broom? One should perform even an insignificant work with respect.</p>
<p><strong>Compiled by a Monk of the Ramakrishna Order</strong></p>
