<h1>What did the luminaries of the age think of Swami Vivekananda?</h1>
<h2>&nbsp;</h2>
<ul>
	<i>Rabindranath Tagore</i>
	<i>Sri Aurobindo</i>
	<i>Balgangadhar Tilak</i>
	<i>Bepin Chandra Pal</i>
	<i>Mahatma Gandhi</i>
	<i>Jawaharlal Nehru</i>
	<i>Subhash Chandra Bose</i>
	<i>Romain Rolland</i>
	<i>Christopher Isherwood</i>
	</i>
</ul>
<h3>Rabindranath Tagore</h3>
<p>If you want to know India study Vivekananda. In him everything is positive and nothing negative.</p>
<p>In recent times in India, it was Vivekananda alone who preached a great message which is not tied to any do's and do's and don'ts. Addressing one and all in the nation, he said: In every one of you there is the power of Brahman (God); The God in the poor desires you to serve Him. This message has roused the heart of the youths in a most pervasive way. That is why this message has borne fruit in the service of the nation in diverse ways and in diverse forms of sacrifice. This message has, at one and the same time, imparted dignity and respect to man along with energy and power. The strength that this message has imparted to man is not confined to a particular point; nor is it limited to repetitions of some physical movements. It has, indeed, invested his life with a wonderful dynamism in various spheres. There at the source of the adventurous activities of today's youth of Bengal is the message of Vivekananda-which calls the soul of man, not his fingers.</p>
<h3>Sri Aurobindo</h3>
<p>Vivekananda was a soul of puissance if ever there was one, a very lion among men, but the definite work he has left behind is quite incommensurate with our impression of his creative might and energy. We perceive his influence still working gigantically, we know not well how, we know not well where, in something that is not yet formed, something leonine, grand, intuitive, upheaving that has entered the soul of India and we say, "Behold, Vivekananda still lives in the soul of his Mother and in the souls of her children."</p>
<h3>Balgangadhar Tilak</h3>
<p>It was Swami Vivekananda who took on his shoulders this stupendous task of establishing the glory of Hinduism in different countries across the borders. And he, with his erudition, oratorical power, enthusiasm and inner force, laid that work upon a solid foundation…. Twelve centuries ago Sankaracharya was the only great personality, who not only spoke of the purity of our religion, not only uttered in words that this religion was our strength and wealth, not only said that it was our sacred duty to preach religion in the length and breadth of the world - but also brought all this into action. Swami Vivekananda is a person of that stature - who appeared towards the last half of the nineteenth century.</p>
<h3>Bepin Chandra Pal</h3>
<p>The message of Vivekananda, through delivered in the term of the popular Vedantic speculation, was really the message of his Master to the modern man. Vivekananda's message was really the message of modern humanity. His appeal to his own people was, "Be men."</p>
<p>…To help man to realize his essential divinity is the object of all religious culture. This is what Vivekananda really meant when he appealed to his people to be men. In the ritual of divine worship of the Brahmin, is used the following text which says: "I am divine. I am none other. I am not subject to grief and bereavement. I am of the True, the Self-conscious and the Eternally Present. I am by nature eternally free." This was the message really of his Master as delivered to the modern world by Vivekananda.</p>
<h3>Mahatma Gandhi</h3>
<p>I have come here [Belur math] to pay my homage and respect to the revered memory of Swami Vivekananda, whose birthday is being celebrated today [6 February 1921]. I have gone through his works very thoroughly, and after having gone through them, the love that I had for my country became a thousand-fold. I ask you, young men, not to go away empty-handed without imbibing something of the spirit of the place where Swami Vivekananda lived and died.</p>
<h3>Jawaharlal Nehru</h3>
<p>Rooted in the past and full of pride in India's prestige, Vivekananda was yet modern in his approach to life's problems and was a kind bridge between the past of India and her present…. He was a fine figure of a man, imposing, full of poise and dignity, sure of himself and his mission, and at the same time full of a dynamic and fiery energy and passion to push India forward. He came as a tonic to the depressed and demoralized Hindu mind and gave it self-reliance and some roots in the past.</p>
<h3>Subhash Chandra Bose</h3>
<p>I cannot write about Vivekananda without going into raptures. Few indeed could comprehend or fathom him - even among those who had the privilege of becoming intimate with him. His personality was rich, profound and complex and it was this personality - as distinct from his teachings and writings - which accounts for the wonderful influence he has exerted on his countrymen and particularly on Bengalees. This is the type of manhood which appeals to the Bengalee as probably none other. Reckless in his sacrifice, unceasing in his activity, boundless in his love, profound and versatile in his wisdom, exuberant in his emotions, merciless in his attacks but yet simple as a child - he was a rare personality in this world of ours….</p>
<p>Swamiji was a full-blooded masculine personality - and a fighter to the core of his being. He was consequently a worshipper of Shakti and gave a practical interpretation to the Vedanta for the uplift of his countrymen…. I can go on for hours and yet fail to do the slightest justice to that great man. He was so great, so profound so complex. A Yogi of the highest spiritual level in direct communion with the truth who had for the time being consecrated his whole life to the moral and spiritual uplift of his nation and of humanity, that is how I would describe him. If he had been alive, I would have been at his feet. Modern Bengal is his creation - if I err not.</p>
<h3>Romain Rolland</h3>
<p>He [Vivekananda] was energy personified, and action was his message to men. For him, as for Beethoven, it was the root of all the virtues….</p>
<p>His pre-eminent characteristic was kingliness. His was a born king and nobody ever came near him either in India or America without paying homage to his majesty.</p>
<p>When this quite unknown young man of thirty appeared in Chicago at the inaugural meeting of the Parliament of Religions, opened in September 1893, by Cardinal Gibbons, all his fellow-members were forgotten in his commanding presence. His strength and beauty, the grace and dignity of his bearing ,the dark light of his eyes, his imposing appearance, and from the moment he began to speak, the splendid music of his rich deep voice enthralled the vast audience of American Anglo-Saxons, previously prejudiced against him on account of his colour. The thought of this warrior prophet of India left a deep mark upon the United States.</p>
<p>It was impossible to imagine him in the second place. Wherever he went he was the first ….Everybody recognized in him at sight the leader, the anointed of God, the man marked with the stamp of the power to command .A traveler who crossed his path in the Himalayas without knowing who he was stopped in amazement, and cried, "Shiva!…</p>
<p>It was as if his chosen God had imprinted His name upon his forehead….<br /> He as less than forty years of age when the athlete lay stretched upon the pyre….</p>
<p>But the flame of that pyre is still alight today .From his ashes ,like those of the Phoenix of old, has sprung anew the conscience of India - the magic bird - faith in her unity and in the Great Massage, brooded over from Vedic times by the dreaming spirit of his ancient race - the message it must render account to the rest of mankind.</p>
<p>His words are great music, phrases in the style of Beethoven , stirring rhythms like the march of Handel choruses. I cannot touch these sayings of his, scattered as they are through the pages of books at thirty years' distance, without receiving a thrill through my body like an electric shock. And what shocks, what transport must have been produced when in burning words they issued from the lips of the hero!</p>
<h3>Christopher Isherwood</h3>
<p>One of the most enchanting things about Vivekananda is the way he was eternally changing sides when he was speaking to different people; he could denounce the British in words of fire, but again he would turn on the Indians and say, "You cannot manufacture one pin, and you dare to criticize the British !" And then he would speak of the awful materialism of the United States, and on the other hand, he would say that no women in the world were greater, and that the treatment of the women in the India was absolutely disgraceful. And so in every way, he was integrating, he was seeing the forces for good, the constructive forces, in the different countries, and saying, "why don't we exchange?" So Vivekananda's revolution was a revolution for everybody a revolution which would in the long run be of just as much use to the British as to Indian. Vivekananda's nationalism, the call to Indian to recognize herself - this again was not nationalism in the smaller sense, it was a kind of super-nationalism, a kind of internationalism sublimated.</p>
<p><strong>Edited by Swami Lokeswarananda</strong> World Thinkers on Ramakrishna-Vivekananda; The Mission, Institute of Culture, Calcutta, 1983</p>

