<h1>What is the significance of Sri Ramakrishna's advent?</h1>
<h2>&nbsp;</h2>
<p><strong>Swami Vivekananda</strong> Sri Ramakrishna The Great Master Sri Ramakrishna Math, Chennai</p>
<p>It is well known from such books as the Smritis that the Divine incarnates Himself again and again for the protection of the Veda, the true religion, and of Brahmana, that is, the teacher of religion.</p>
<h3>Sri Ramakrishna's foremost Disciple</h3>
<p>Even as a stream falling down a precipice gains in speed, and a wave rising after a fall swells higher, so after each downfall, as history demonstrates, did the Aryan society shed its morbidities and emerge more glorious and vigorous under the compassionate guidance of the Divine.</p>
<p>Rising again after each fall, our society reveals more of the eternal perfection hidden within; and the Divine, the internal controller of all beings, likewise manifests more and more of His real nature in successive incarnations.</p>
<p>Again and again did this land of Bharata faint away, and again and again did the divine Lord manifest Himself and re-awaken it.</p>
<p>But in the past no new-moon night of sorrow veiled this holy land with such a dense darkness as at present. That night is all but gone, it being now at the fag end of its last quarter. However, the last fall of the country has been, as it were, to the bottom of the ocean, whereas, by comparison, all previous falls have been but into the hoof-marks of a cow.</p>
<p>Therefore, compared with the splendour of this present awakening of the Aryan society, previous awakenings will appear as lacking in lustre, like stars before the effulgence of the sun. And compared with the great vigour of this re-awakening, similar occurrences of the past will appear as child's play.</p>
<p>On account of the lack of fit persons to prevent the calamity, the fragments of the various aspects of the eternal religion lay scattered in all directions during the present downfall, in the forms of petty sects. It was partially preserved in some places and utterly lost in others.</p>
<p>The most compassionate divine Lord has manifested Himself far more fully in this modern age, in the aforesaid form of the incarnation of the age, than He ever did in any other age, playing as He has done on the entire gamut of all the spiritual moods and experiences and utilizing to the utmost all arts and sciences.</p>
<p>In consequence of this fact, during this renaissance, the descendants of Manu, invigorated by this new strength, will be able not only to piece together the fragmented and scattered mass of spiritual knowledge, but also to re-discover the lost branches of arts and sciences, and to enrich their lives by the realization of those ideas and ideals through proper understanding.</p>
<p>Hence is being preached the harmony of all noble ideas and ideals at the dawn of this great age. And this infinite and eternal grand ideal that lay embedded and hidden in the ancient scripture and religion of India is being loudly proclaimed in society.</p>
<p>This new faith of the age is the fruitful sources of all blessings to the world, especially to India (Bharata); and Sri Bhagavan Ramakrishna, the founder of this new religion of the age, is the reformed manifestation of the ancient holy founders of the religions of the past. Have faith in it, O man, and grasp it!</p>
