<h1>Universal Temple at Nagpur</h1>
<h2>&nbsp;</h2>
<h3>What is the significance of a Temple for Sri Ramakrishna?</h3>
<p>This article contains excerpts from the talk given by Srimat Swami Ranganathanandaji Maharaj during the foundation-laying ceremony of the Universal Temple at Chennai. (Swami Ranganathanandaji Maharaj was the 13th President and at the time of this lecture, was, the Vice-president of the Ramakrishna Math and Mission worldwide)</p>
<h3>Srimat Swami Ranganathanandaji</h3>
<p>When we speak of a temple, we often have a very narrow conception of it. We have hundreds of temples. We go there sometimes, talking all the time, pay four annas to the priest to do some puja, and then come away. Our temple-going has become a simple, and often meaningless act. It doesn't produce any change in the individual. Today, you need a new type of temple, which will make for a change for the better in your own character. That is what Sri Ramakrishna is going to give. He never started a new religion. He never preached any creed or dogma. He only blessed every human being: 'Let your spiritual consciousness be awakened!'</p>
<p>Whether you go to a temple, a church or a mosque, what is needed is spiritual awakening, and the character that comes out of that awakening. This we missed all these centuries. But in the modern age, this will be the central theme of religion and temple-worship.</p>
<p>Temple-worship has been recognised as an important part of spiritual life. A teacher like Bhagavan Ramanujacharya spoke of the image in the temple as an incarnation of God archavatara, like Krishna or Rama or Ramakrishna. And in your own heart, there is the antaryamin the inner Self, the avatara in the heart of every human being. The archa or image is also an avatara. That is the concept in our spiritual tradition.</p>
<p>With Sri Ramakrishna's advent, temples will become more dynamic, making for high character-development and, above all, the spirit of service of human beings and even animals.</p>
<p>We, as a nation, have failed in one field - human relations. We have succeeded in relating ourselves to images in temples; but we have utterly failed in relating ourselves to human beings around. I used to ask people, 'When you go to a temple to pray, what do you pray for?' Their answer would be, 'Oh God, give me this, give me that ..' Did you ever pray for something to be given to somebody else? We never did it. NEVER. We are so self-centered! What is the use of going to temples when we are self-centered! There will be no use whatsoever in temple-going unless we change our character into something positive. Therefore this great teaching comes to you, that behind the temple of Sri Ramakrishna is a wonderful idea of service of people - for the common people, for the uncommon people, for all people. That seva-dharma is at the back of this great temple project.</p>
<p>Behind any Sri Ramakrishna temple you will find various types of service schools, colleges, hostels, tribal work, relief and rehabilitation work during natural calamities, etc. This seva-dharma is a part of Ramakrishna-temple worship. Such temple worship has a great role to play in the future India, where service becomes the central theme service of God in the temple, and service of God in human beings, outside the temple. This teaching is there in our Upanishads, in the Gita, and in the Srimad Bhagavatam! All these centuries we had this teaching, but we hardly practiced it.</p>
<p>We did not know how to relate to other human beings. We quarrel, we fight, we go to court, but we do not deal with other human beings in a friendly way. We have to learn that lesson today.</p>
<p>In Swami Vivekananda's teachings, you find this central Vedantic Truth the divinity in every human being. Look upon a human being, not in terms of his or her caste, creed, colour, race or anything else but see him or her as a spark of divinity. We have this great teaching in the Gita, (18.61) where Sri Krishna himself says Ishvarah sarva bhutanam hrddese arjuna tishthati 'O Arjuna, I am in the heart of all beings as their antaryami'. So, respect every human being. That is what we did not do. Our practice was that of untouchability, suppression of the common people, even suppression of women. That is how we conducted our society during the last thousand years.</p>
<p>A peaceful social revolution to correct this situation will come from a temple like this because, behind it, is a profound philosophy our ancient Vedanta philosophy, which is the philosophy of Sanatana Dharma, and that philosophy insists that you must see God not only in a temple, but also in every human being. So worship him, serve him. That is the language used in the Srimad Bhagavatam.</p>
<p>I often used to wonder, that though we have had hundreds and thousands of Bhagavata saptahas for many years, yet we have never caught the spirit of this beautiful teaching. You get it in the third skandha (chap. 29.21-26) of the Srimad Bhagavatam, where God's incarnation as Kapila is giving spiritual advice to his mother Devahuti, at her request. There Kapila says:<br />
Aham sarvesu bhutesu bhutatma<br />
avasthitah sada;<br />
Tam avajnaya mam martyah<br />
Kurute arca vidambanam
</p>
<p>'I am always present in the heart of all beings, O Mother! People neglect me there, insult me there, and offer me showy worship in the temple! What kind of worship is it?'</p>
<p>Ahm uccavacaih dravyaih<br />
kriyaya utpannaya anaghe;<br />
Naiva tusye arcito arcayam<br />
Bhutagramavamaninah -</p>
<p>'Mother, I do not accept the worship of that person, though he or she may spend crores of rupees on elaborate rituals, but if, behind it, there is disrespect to me present in all living beings.'</p>
<p>Then, finally, comes a beautiful statement which Swami Vivekananda had in his mind when he spoke, in this Madras city in 1897, on the great subject, The Future of India. We must remember that the finest nation-building speeches, humanistic speeches, were delivered by Swamiji in Madras.</p>
<p>In that fine lecture, (Complete Works, vol. 3. p.300), he said:</p>
<p>'For the next fifty years, this alone shall be our keynote - this, our great Mother India. Let all other vain gods disappear for the time from our minds. This is the only god that is awake, our own hands - "everywhere his hands, everywhere his feet, everywhere his ears, he covers everything." All other gods are sleeping. What vain gods shall we go after and yet cannot worship the god that we see all round us, the Virat? When we have worshipped this, we shall be able to worship all other gods. Before we can crawl half a mile, we want to cross the ocean like Hanuman! It cannot be. Everyone going to be a Yogi, everyone going to meditate! It cannot be. The whole day mixing with the world with Karma Kanda, and in the evening sitting down and blowing through your nose! Is it so easy? Should Rishis come flying through the air, because you have blown three times through the nose? Is it a joke? It is all nonsense. What is needed is Chittashuddhi, purification of the heart. And how does that come? The first of all worship is the worship of the Virat - of those all around us. Worship It. Worship is the exact equivalent of the Sanskrit word, and no other English word will do. These are all our gods - men and animals; and the first gods we have to worship are our countrymen. These we have to worship, instead of being jealous of each other and fighting each other. It is the most terrible Karma for which we are suffering, and yet it does not open eyes!</p>
<p>In the same note, Srimad Bhagavatam says, (3.29.27):<br />
Atha mam sarvesu bhutesu bhutatmanam krtalayam;<br />
Arhayet danamanabhyam maitrya abhinnena Chakshusa</p>
<p>What a profound utterance! After having said all this, now Kapila is saying: 'Therefore, mam arhayet, 'worship me'. Where? sarva bhuteshu, 'in all beings'. Why? bhutatmanam, 'I am the Self of all beings'; kritalayam, 'I have a big temple already built in that particular body'; arhayet, 'worship me there'.</p>
<p>But how to worship God in man? Worshipping an image is easy. You can give plenty of food, and you can take the food back home too. But when you worship God in man, a different method is needed. That is beautifully expressed by two great words in the sloka: dana-manabhyam, 'through dana, gift, and mana, respect. Remove their wants. If they are uneducated, give them education; if they are suffering, give them consolation; if they are helpless, help them. In this way practice dana. And while doing so, show mana, respect to them. Don't throw a coin before a person with disrespect. So, dana must be combined with mana. Arhayet danamanabhyam. arhayet, worship (me there); not merely serve.</p>
<p>And when you do so what should be your attitude? Maitreya, with the attitude of 'I am a friend of yours.' I have come to worship God through you.</p>
<p>Take for example, village work. If you go to work in a village, the villagers become suspicious. They think: "These fellows have been exploiting us all these years; for that, they have come again.' They have seen only that in their life - constant exploitation of rural people by the people of the towns and cities. So this second idea, maitrya, is very important.</p>
<p>But that is not enough; another value is also necessary; that brings the last word, a most profound Vedantic utterance, abhinnena Chakshusa, 'with an attitude of non-separateness' the attitude that we are all essentially one. You may be poor and I may be rich, but we are one. You may be a Hindu, a Muslim or a Christian, I may be somebody else, but we are essentially one. This is a wonderful word abhinna chakshu! Vedanta condemns all bhinna chakshu, that 'we are separate,' 'we are high,' 'we are low,' and all such attitudes. And yet our society is even today full of bhinna chakshu based on casteism and communalism and feudalism! We have to cultivate this Vedantic abhinna chakshu.</p>
<p>So this profound sloka will make our temples dynamic, make our temples centres of both spiritual development and human welfare. The two must go together.</p>
<p>We have in our country millions of illiterate, starving, and helpless people. Out temples and our temple-going had no meaning till now, as far as they were concerned.</p>
<p>Why did we never ask this question, 'Why are these people starving in our country?' We should have asked this question whenever we went to a temple. We never asked this question! Is there a way to correct this? We are now asking this question because Swami Vivekananda brought this problem before us through his lectures and letters filled with sorrow and compassion. In his The Future of India lecture, you will find his humanistic passion. All his Madras lectures are very inspiring. My Plan of Campaign, the first lecture, Vedanta and its Application to Indian life, The Work before Us, Sages of India and The Future of India, every one of them is extempore, and full of beautiful language and inspiring ideas. How to make this nation great, how to produce great people in a great nation - that is the theme Swamiji emphasized in all these lectures. So here is a temple we are inaugurating today and behind this is the broad vision of humanistic love, and service to humanity, irrespective of caste and creed or gender, seeing the one Divine Self in every human being.</p>
<p>Humanism came along with modern science too, but it is a purely materialistic humanism. It takes into account only the externals, it cannot see the deeper dimension of the human being. Even in Marxism, there is humanism, but it is very limited. Vedanta alone gives you an unlimited spirit of humanism, without any distinction between people who are atheistic or agnostic or religious. It proclaims that all people are human beings with a spark of divinity within them whether they know it or not, and that we shall respect them and serve them.</p>
<p>This kind of humanism is what you get in our great Vedanta philosophy and spirituality which Swamiji preached, both in the East and in the West. And a temple of Sri Ramakrishna will help people to combine service to humanity with one's spiritual practices and worship in the temple. What you get through japa and meditation and worship, you pour out as service. As the German mystic Eckhart has said, 'What we take in by contemplation, that we pour out in love and service.' That is what we need! But we have never done it before. We do go to a temple, even weep there, and come out and cheat half-a-dozen people later on; this is how we separated life and religion; both have suffered thereby; now we shall mix the two.</p>
<p>That is the supreme message of yoga in the Gita. Though our people have read the Gita, they never practiced even a bit of it. But this time, we shall read, we shall understand, we shall apply and practice! Swami Vivekananda repeatedly said, that we need Practical Vedanta! But how to practice it in day-to-day life? Everyone can do it. There is no need for any high education in order to practice this Practical Vedanta. The things that are needed are high character, a spirit of service, and an intense humanistic impulse. All these will come out of a Sri Ramakrishna temple. That is what we want. No distinction of caste and creed, colour and race. That is the most universal attitude that we have to develop in India today. And as I said in the beginning, 'Let your spiritual consciousness be awakened' is Sri Ramakrishna's blessing to humanity. When that is awakened, all values will come - love, compassion, spirit of service. That is true religion, the science of spirituality, said Vivekananda.</p>
<p>Swamiji defines religion in a scientific language as 'the manifestation of the divinity already in man.' That is the religion that will come out of a Sri Ramakrishna temple. Not only we in India, but people in the whole world study Ramakrishna - Vivekananda literature today. I have seen Russians in Moscow University listening to my lecture on the great teaching of Swami Vivekananda's humanism. During the lecture I conveyed the central truth of Vedanta: "There is a spark of divinity in every human being.' One professor got up and said, "This is a wonderful idea; we have never heard of it; I want to know more about the subject.' All over the world, people have been inspired by it is great vision, 'man, physically limited, spiritually unlimited'. The infinite is hidden here.</p>
<p>'Divine is in the heart of all'. 'I am the Atman,' 'I am the infinite Self behind the body-mind complex', 'Body-mind complex is perishable, Atman is imperishable' - these ideas are attracting attention even from nuclear scientists, biologists, and others all over the world.</p>
<p>The scientific search for the imperishable was the work of the sages of the Upanishads; they discovered the imperishable behind the perishable; that is real religion. What did Sri Ramakrishna do in Dakshineswar? He never went to school or college, and yet the most educated people came to him just like children, to learn from him. Why? He realized the imperishable, the unseen. Everything is there. That is why a Vivekananda of brilliant intellect becomes a child before Sri Ramakrishna. That is Sri Ramakrishna. It is his message that will bring harmony in this society of ours, and also bring high character and energy. There is something unique about Sri Ramakrishna and the Holy Mother; Sri Ramakrishna did many sadhanas or spiritual practices, but he did one unique sadhana which no saint before had done. At midnight, he cleaned the latrine of an untouchable in Dakshineswar, praying to the Divine Mother, please remove from my mind any notion, of being superior as a Brahmin, make me a servant of all'. And the Holy Mother, coming from a brahmana family, fed a muslim youth and cleaned his ucchistam. Again, she received a mleccha woman, Miss Margaret Noble, later known as Sister Nivedita, made her sit on her own bed and talked with her. This value orientation of India will come only from the Vedantic teaching 'Manifest the divine within'.</p>
<p>I want to mention here one more idea before I close. In the Mahabharatha there is a beautiful sloka: How many energies are there in every human being? That sloka gives you three energies, three sources of strength.</p>
<p>First is bahu balam, muscular strength. We have it, and we are increasing it and spoiling our politics also by bahu balam.</p>
<p>Second is buddhi balam, strength from intellect graduates, PhDs., all that is good but it also can be harmful. Most of the evils in our nation now are coming from educated people; so we can see that in our country there is bahu balam and buddhi balam.</p>
<p>But the third one is what is most valuable and effective. This is called Atma balam, strength coming from the Atman. If a man brings me a million rupees to corrupt me, what is the strength in me which makes me say 'No' to it? Not the bahu balam, not the buddhi balam. In fact, the buddhi balam is easily purchased. It is very easy to purchase somebody's buddhi. But when Atma balam is there, you can say 'No' immediately. 'I don't care. I've got better things to do.'</p>
<p>That Atma balam is missing in India today. That Atma balam has to come. Sri Ramakrishna will give that Atma balam to everyone, so that our nation will have not only economic development, but also character development. That is missing very badly today. We want to develop it fully. That is the importance of Sri Ramakrishna, Swami Vivekananda, and the Holy Mother Sarada Devi to the world today.</p>
<p>On this occasion it is very important to mention the Holy Mother, an uneducated utterly simple village woman, but in her was a mother; a mother-heart, matrhrdayam, embracing the whole of humanity.</p>
<p>Our mothers can love only their own two or three children. The others are all foreigners to our mothers. Now, our mothers will have to change. They will develop a real mother-heart. Both men and women can develop this mother-heart. That is what Holy Mother will teach us; a mother's heart full of infinite love and the spirit of service. We in India have brain, but our heart is very very contracted. Let us expand the heart and then combine it with the brain; then we will have in our nation the finest people in the world.</p>
<p>This is what you can expect from Sri Ramakrishna's worship and the study of the unifying, strengthening and universal Ramakrishna Vivekananda literature. That is the attitudinal revolution that will come to our nation in the coming decades - it is bound to come. At this critical time, we have to save our nation and the world from destruction, from the onslaught on religion by the materialism of the modern science. Only Swami Vivekananda's Vedanta can do it.</p>









