<h1>Who was Sri Sarada Devi (Holy Mother)?</h1>
<h2>&nbsp;</h2>
<h3>Where Sarada Devi was born</h3>
<p>No greatness has sprung up and got reared and even flowered in greater obscurity and silence than that of Sarada Devi. She was born in the obscure village of Jayrambati in West Bengal, India, on 22 December 1853. Her advent coincided with the brightening of the family fortunes of her poor but pious parents, who enfolded her in tender love and care. Even as a child she was active and hardworking, and helped her mother in her household chores. She was hardly six when she was betrothed to Sri Ramakrishna who was then twenty-three and who was passing through the stormy period of his spiritual sadhanas and realizations. Through this betrothal, little Sarada entered into the current of the life of one who, in his God-intoxication passed most of his life in divine ecstasies and visions, and the rest in soulstirring conversations with earnest souls, conveying a message of radiant spirituality to the modern world.</p>
<p>It was a strange marriage; for it remained unconsummated in the physical plane, but found its spiritual consummation in a union of souls on the occasion of the Shodashi-puja in 1872. This was the culminating act of Sri Ramakrishna's spiritual sadhanas when he worshipped the Divine Mother of the universe in the person of his wife, at the end of which the worshipped and the worshipper entered into deep Samadhi and realized their spiritual identity. Thenceforth they became as one soul functioning in two bodies, and Sarada Devi assumed her equal role in the fulfillment of the mission of Sri Ramakrishna.</p>
<p>Sri Ramakrishna himself recognized the spiritual eminence of Sri Sarada Devi. Unlike the general run of spiritual aspirants who forsake all worldly connections on entering the religious life, for which there is the sanction of religious law and custom behind them, Sri Ramakrishna welcomed Sarada Devi to his side when she, coming of age, came to claim her rights over him.</p>
<h3>Studio picture of Sarada Devi (Calcutta 1905)</h3>
<p>It is a deeply moving episode in their lives, which helps to reveal the stuff of both. Sri Ramakrishna was in Dakshineswar, passing through storms of spiritual moods and experiences; except on the two occasions of his brief visits to his native village, he had not met his wedded wife these twelve long years and seemed apparently to have forgotten her.</p>
<p>Sarada Devi, now about eighteen, entered his room late at night after an arduous journey from her native village in the company of her father. She had her fears in her heart proceeding from the gossip she had heard in her village about the deranged condition of her husband's mind, and her own knowledge of his utter indifference to worldly concerns. But Sri Ramakrishna, though a bit surprised at her sudden arrival, welcomed her very cordially, and accommodated her in his own room for facility of her medical attention, and arranged for the medical care of her body which had been ravaged by illness and fatigue during the long trek. She found in him the same loving divine husband whom she had known during his previous visits to the village. When she had settled down, Sri Ramakrishna one day addressed her thus: 'As for me, the Mother has shown me that she resides in every woman, and so I have learned to look upon every woman as Mother. That is the one idea I can have about you; but if you wish to drag me into the world, as I have been married to you, I am at your service.'</p>
<h3>Nahabat - where Sri Sarada Devi lived at Dakshineshwar</h3>
<p>To this challenging question of her divine husband, Sarada Devi gave a straightforward answer: 'Why should I desire to drag your mind down to the worldly plane? I have come only to help you in your chosen path. I desire only to live with you and serve you and to learn of you.'</p>
<p>This reply of his pure and spotless wife pleased Sri Ramakrishna immensely and he experienced a great accession of spiritual strength. His mission in the world of calling humanity back to an awareness of its inborn divine nature is not to be a lonely struggle; he recognized in Sarada Devi a companion in this noble mission; and within a year of her arrival, he verified the truth of this exalted view of his wife through the Shodashi-puja experience referred to above.</p>
<p>From now on till the end of his life, for full fourteen years, Sarada Devi served the person of Sri Ramakrishna and the large number of disciples and devotees visiting him, with a rare devotion and self-effacement unrivalled in human history. It was also the period of her intense spiritual education under her divine husband. She has referred to this period as a continuous experience of intense bliss. Months together they lived in the same room and slept in the same bed, with no trace of carnal thought in the mind of either. Their minds constantly soared in the region of divine awareness and bliss; each stood transfigured to the other; and both became instruments for the working out of the divine will. The immense store of spiritual energy-<i>divine Shakti</i>-which was generated by the sadhanas of Sri Ramakrishna and Sarada Devi contains the promise of the spiritual evolution of modern humanity which keenly feels its own tragic aspiritual poverty in the midst of abundant material wealth.</p>
<h3>Sri Ma - The Holy Mother (Udbodhan, 1913)</h3>
<p>Sri Ramakrishna passed away in 1886. Sarada Devi was thirty-three at that time. Having lived in a non-physical plane of relationship with her husband, she did not experience the feeling of widowhood at his death. To her he continued to be a living reality to the end of her days. And for the next thirty-four years she lived a life, complex in its roles and varied in its riches, and withal silent and sweet, that gained for her the endearing title of 'Sri Ma', 'the Holy Mother', by which she is known ever since.</p>
<h3>Mother and Her 'family'</h3>
<p>The Holy Mother was called upon to be the spiritual guide of the monks of the Ramakrishna Order constituted initially of Sri Ramakrishna's direct disciples under the leadership of Swami Vivekananda, and to be the guru of an ever-increasing circle of spiritually hungry men and women. Her spiritual eminence and the divine power of the personality enabled her to fulfill this mighty role with ease and naturalness. But it was in the role of a household woman, in the midst of her own family circle consisting of her worldly-minded brothers, sisters-in-law, and their children, that the Holy Mother manifested a unique facet of her character and personality.</p>
<p><strong>(L to R: Sannyasini Gauri Mata Puri Devi, Durga, Radhu, Holy Mother, Maku, Kusum, Hari's mother; Udbodhan, 1909)</strong></p>
<p>It is this aspect of her personality that provides a shining example of practical spirituality capable of inspiring all men and women. The nun shone through the householder, and both through the heart of an all-loving mother. Far from shunning a distracting world, she embraced it and enfolded it in her love. And in the midst of a thousand distractions, she preserved the naturalness of her personality.</p>
<h3>Temple dedicated to Holy Mother at Belur Math</h3>
<p>Verification is the proof of a theory or a claim. The test of life alone proves the genuineness of a moral virtue or a spiritual value; virtues are tested more in ill-fortune than in good fortune. To maintain poise and grace in good weather is easy enough; but it is only bad weather that tests their genuineness. The calmness, poise, and grace, and the spirit of unobstructed love and self-effacing service, which Sarada Devi expressed in her day-to-day life in the context of a highly distracting environment of sheer worldliness, proclaims the supremely uplifting power of godliness and spirituality. The possession of the power by a man or woman makes him or her pure and holy. The expression of this power in life is love. Sarada Devi was the very personification of this purity, holiness, and love which is the meaning of the ideal of motherhood at its highest and best. This power lies embedded in the heart of very woman. An ordinary woman captures in her life only a fraction of this ideal by which she shines in her loving kindness and holiness. A merely biological function becomes elevated through the infilling of a spiritual value. But this spiritual value shone in its fullness, even outside the biological context, in the personality of the Holy Mother, demonstrating thereby the ideal in its pure form. Out of the abundance of her heart Sarada Devi gave of her love to one and all without any distinction and, by so doing, justified the endearing epithet of 'the Holy Mother'.</p>
<p>Herself out of the ordinary in all basic values of character and personality, but hiding these under the mantle of the simple and the ordinary in social and physical make-up, the Holy Mother eludes the grasp of ordinary minds, but reveals her true form to all seekers of basic values. Did not Sri Ramakrishna say of her: 'She is Sarasvati, the goddess of Wisdom, come to give spiritual knowledge to humanity'? And had she not also said of herself: 'Sri Ramakrishna has left me to manifest the ideal of divine Motherhood'?</p>
<h3>Mother and Sister Nivedita (Calcutta 1998)</h3>
<p>In her life and in her teachings she has left a balm for suffering humanity in search of light and peace. Her love knew no distinctions of sex, creed, or race. It emboldened and uplifted the Muslim labourer Amzad as much as the sannyasin Saradananda, the gifted Sister Nivedita as much as the simple 'mother of Annapurna'.</p>
<h3>Holy Mother, 1899</h3>
<p>The Holy Mother's deathbed advice to the latter is typical of her universal personality and depth of insight. To the 'mother of Annapurna' sorrowing at the thought of the Holy Mother's imminent passing away, she spoke these words of uplifting consolation and strength:</p>
<p>If you want peace of mind, do not look for faults in others. Rather look out to discover your own weakness. Learn to make the whole world your own. No one here is an alien or a stranger, my child. The whole world is your own.</p>
<p>Let me conclude this tribute with the beautiful Sanskrit verse composed by Swami Abhedananda, a direct disciple of Sri Ramakrishna, in praise of the Holy Mother's pure nobility:</p>
<p>Whose character is all pure and whose life is similarly pure; who is the embodiment of purity divine, that shining goddess I salute again and again.</p>
<p><strong>Swami Ranganathanandaji</strong> Sri Sarada Devi the Great Wonder Advaita Ashrama, Mayavati; 1984</p>

