<h1>What was the life story of Sri Ramakrishna?</h1>
<h2>&nbsp;</h2>
<p><strong>The Apostles of Sri Ramakrishna</strong> Compiled and Edited by Swami Gambhirananada Advaita Ashrama; Mayavati; June 1995</p>
<p>In the beginning of the last century, India was passing through a great crisis. With the impact of Western civilisation and the spread of English education, the Indians began to lose interest and faith in their own culture. Amongst the English educated people of India there were very few who had a genuine appreciation of Indian culture, though they were born on Indian soil and had the heritage of India's past.</p>
<h3>Sri Ramakrishna</h3>
<p>At that time was born, in an out-of-the-way village of Bengal, one whose life was an unconscious but spontaneous and powerful protest against disregard for the value of Indian religion and culture. It was a strange, divine dispensation that while in Calcutta, the then metropolis of India and the citadel of English education, the Christian missionaries were criticising and abusing Hinduism as idolatrous and a large number of English educated Indians even joined or sided directly or indirectly with this proselytising body, Sri Ramakrishna was revitalising the truths of Hinduism by his intense Sadhana (spiritual endeavour) and wonderful realisations at the temple-garden of Dakshineshwar, four miles north of the city. And he soon became the powerful instrument of turning the mind of India again to the strength and beauty of its own religious and cultural heritage.</p>
<h3>The spot where Thakur was born</h3>
<p>Sri Ramakrishna was born on 18th February 1836 at Kamarpurkur, an obscure village in the district of Hooghly. His parents were pious, orthodox Brahmins, and his family surroundings were such that no ray of Western civilisation had any access there. Sri Ramakrishna was a child of nature, and as a matter of fact, throughout his life he remained such, untouched by the least worldliness. The sight of anything beautiful in nature, or the stirring up of emotion by a religious sentiment, would throw his mind into a super conscious state, and in that condition he would remain for a long time oblivious of his surroundings. While his guardians pressed him to receive education at the village school, the boy found great delight in remaining in the open fields, acting religious dramas with his companions or singing devotional music with them. Finding that his life was going to be spoilt in the village atmosphere, his eldest brother took him to Calcutta, where better facilities might be had for education. But the boy was untractable; he would not undergo the drudgery of an education which was simply a "means of earning bread", though he was athirst for that knowledge which would solve the problem of life and death. His guardian gave up the case as hopeless and let him have his own way.</p>
<h3>Kali Temple Dakshineshwar</h3>
<p>Sri Ramakrishna was, however, persuaded to take up the priestly duties in the temple of Kali at Dakshineshwar, which was opened in 1855. Here he found congenial work in an atmosphere which was to his liking. But Sri Ramakrishna's was not a mind to be satisfied with the routine duties and the mechanical performance of rituals in the temple. As he was offering worship from day to day before the image of Kali, the thought that oppressed him was, "Is She a living presence, or simply a stone image before which I am bowing down every day?" He was passing through a great mental agony, and this simple childlike thought became almost devouring to him. Day and night he would give vent to his feelings in tears till at last he experienced a living and vivid presence in the image far beyond the possibility of any doubt.</p>
<h3>The living presence of Mother Kali at Dakshineshwar</h3>
<p>After that the Goddess Kali - or the Divine Mother as he would call Her - was to him a greater reality than any material object. He would talk to Her, he would pray to Her, he would hear Her voice - nay, he would feel the very breath of Her nostrils. It is not for us to prove how that was possible, but it was a fact for him.</p>
<p>Sri Ramakrishna was not satisfied with a single form of Sadhana, he undertook almost all the forms of spiritual practice advocated by Hinduism in the different periods of its history. So it is said that he represented in one life the whole religious history of India's past. It was a unique phenomenon. Whereas an aspirant usually undertakes one mode of spiritual practice and considers himself blessed if he can succeed in that, here was one who performed countless forms of Sadhana and in every one attained success in an incredibly short time. Not being content even with that, he practised Islam and realised also the truth of Christianity. Thus he realised from his own personal experience that all religions are true and that fundamentally there is no difference between them. This is a teaching on which he laid great emphasis.</p>
<p>During the last few years of his life he lived more in the superconscious than in the conscious plane. He remained constantly in tune with the Infinite, and the slightest thing having the remotest association with any religious idea would throw his mind into ecstasy, in which he would be totally oblivious of his surroundings-nay, of his very bodily existence</p>
<p>Such being the condition of his mind, any worldly thought was impossible for him. He was the embodiment of renunciation. Even if inadvertently his fingers touched any metallic currency, his whole body would recoil, representing as the coin did to his mind the human desire for sense-pleasure. Though in the world, his mind was beyond the reach of the world. His mind was buried in visions, ecstasies and divine communion.</p>
<p>Such a powerful personality could not remain unknown. People began to flock to him for religions inspiration and for the solution of the deeper problems of life. Persons of diverse types and from different walks of life began to come to him. Kristodas Pal - the great national leader, Bankim Chandra Chatterjee - the great Bengali prose writer. Girish Chandra Ghosh-the great actor-dramatist and the father of the Bengali stage. Dr. Mahendra Lal Sarkar-the great physician, Shashadhan Tarkachudamani -the leader of the orthodox Hindu community and an erudite Sanskrit scholar. Keshab Chandra Sen - the great Brahmo leader, to name only a few, were amongst those prominent men of the day who met him and drank in the words of wisdom that fell from his lips. There were innumerable devotees-men and women-whose lives he completely metamorphosed and turned into pure gold. But his chief concern was with a band of disciples, both men and women, whose lives he moulded with particular care for the fulfillment of his future mission.</p>
<p>In the middle of 1885 Sri Ramakrishna fell ill, and for facilities of treatment he had to be moved to Shyampukur in Calcutta in the beginning of October that year. Subsequently, in December, he was taken to a garden-house at Cossipore, where he went into Mahasamadhi on the 16th August 1886.</p>
<p>This sad period, however, served indirectly to strengthen the bond of love among the disciples of the inner circle and gave better opportunity to Sri Ramakrishna to lay the foundation of his future mission surely and adequately. He had to deal with three classes of disciples-the women headed by his own consort Sri Sarada Devi, the Holy Mother; the young men led by Narendra Nath who renounced the world afterwards; and the lay disciples like Nag Mahashaya Girish Chandra Ghosh, and others.</p>
<h3>Panchavati</h3>
<p>Panchavati (at the Dakshineshwar Temple Complex)-where Sri Ramakrishna practiced austerity. This was once a wooded area - like a jungle... This is a modern-day picture by <strong>Alan Perry</strong> - with what remains of it today</p>
<h3>Sri Ramakrishna in Samadhi</h3>
<p>A rare photo of Sri Ramakrishna in samadhi taken during a kirtan at Keshab Sen's house on 21 September, 1879. See page 712 of The Gospel of Sri Ramakrishna.</p>
<h3>The Cossipore Garden-house</h3>
<p>The place marked x is where Thakur blessed lay devotees in a mood of divine consciouness. This was called the Kalpataru Day as Thakur became Kalpataru - the wish fulfilling tree</p>
