<h1>Almano Moksharth Jagad Hitay Cha</h1>
<h2>&nbsp;</h2>
<p>Nagpur is the geographical center of India - the "Zero Milestone".</p>
<p>From this vantage point, the Ramakrishna Math Nagpur has ceaselessly worked out its mission of "Atmano Mokshartham Jagaddhitay Cha" - The good of the self and the good of all - for over 75 years.</p>
<p>The Ramakrishna Math Nagpur invites you to explore this website, both from the view point of learning more about the Math and its activities in Nagpur, and also from the viewpoint of exploring the Ramakrishna Movement through the lives of its Personalities</p>
<p><i>"... How to worship God in man? Worshipping an image is easy. You can give plenty of food, and you can take the food back home too. But when you worship God in man, a different method is needed. That is beautifully expressed by two great words in the sloka: dana-manabhyam, 'through dana, gift, and mana, respect. Remove their wants. If they are uneducated, give them education; if they are suffering, give them consolation; if they are helpless, help them. In this way practice dana. And while doing so, show mana, respect to them. Don't throw a coin before a person with disrespect. So, dana must be combined with mana. Arhayet danamanabhyam. arhayet, worship (me there); not merely serve."</i></p>
<p><i>Srimat Swami Ranganathanandaji Maharaj during the foundation-laying ceremony of the Universal Temple at Chennai</i></p>
<p>When we speak of a temple, we often have a very narrow conception of it. We have hundreds of temples. We go there sometimes, talking all the time, pay four annas to the priest to do some puja, and then come away. Our temple-going has become a simple, and often meaningless act. It doesn't produce any change in the individual. Today, you need a new type of temple, which will make for a change for the better in your own character. That is what Sri Ramakrishna is going to give. He never started a new religion. He never preached any creed or dogma. He only blessed every human being: 'Let your spiritual consciousness be awakened!'</p>
<p><i>Srimat Swami Ranganathanandaji Maharaj during the foundation-laying ceremony of the Universal Temple at Chennai</i></p>
<p>Foreign Contributions financial statments | Register yourself as an alumni</p>
