<h1>In College</h1>
<h2>&nbsp;</h2>
<p>At college Narendranath began to interest himself more seriously in studies. Apart from the usual college curriculum, he avidly studies western logic, the abstruse philosophy of Herbert Spencer, the systems of Kant and Schopenhauer, the mystical and analytical speculation of the Aristotelian school, the positivist philosophy of Comte, and John Stuart Mill's Three Essays on Religion. He also mastered the ancient and modern history of Europe and the English poets like Shelley and Wordsworth. He even took a course in physiology with a view to understanding the functioning of the nervous system, the brain, and the spinal cord.</p>
<p>But this contact with western thought, which lays particular emphasis on the supremacy of reason, brought about a severe conflict in Narendranath. His inborn tendency towards spirituality and his respect for the ancient traditions and beliefs of his religion which he had imbibed from his mother, on the one side, and his argumentative nature coupled with his sharp intellect which hated superstition and questioned simple faith on the other, were now at war with each other. Under a deep spiritual urge, he was then found observing hard ascetic practices, staying in his grandmother's house, away from his parents and other relatives, following a strict vegetarian diet, sleeping on the bare ground or on an ordinary quilt, in accordance with the strict rules of brahmacharya. From youth, two visions of life had presented themselves before him. In one, he found himself among the great ones of the earth, possessing riches, power, honour, and glory, and he felt himself capable of renouncing all worldly things, dressed in simple loin- cloth, living on alms, sleeping under a tree, and then he felt that he had the capacity to live thus like the Rishis of ancient India. It was, however, the second vision that prevailed in the end, and he used to sleep with the conviction that by renunciation alone could man attain the highest bliss.</p>
<p>In his eagerness for spiritual illumination he went to Devendranath Tagore, the leader of the Brahmo Samaj, and asked him: "Sir, have you seen God?" The old man was embarrassed by the question, and replied, "My boy, you have to eyes of a Yogi. You should practice meditation." The youth was disappointed, but he received no better answer from the leaders of other religious sects whom he approached with the same question.</p>
<p>At this critical juncture he remembered the words of his professor, William Hastie, who, while speaking of trances in the course of his lectures, had said, "Such an experience is the result of purity of mind and concentration on some particular object, and is rare indeed, particularly in these days. I have seen only one person who has experienced that blessed state of mind, and he is Ramakrishna Paramahamsa of Dakshineswar. You can understand if you go there and see for yourself." ... now in his trouble, the young seeker decided to have yet one more try to solve his problem.</p>
<p><strong>At the first meeting:</strong></p>
<p>Approaching him (Sri Ramakrishna at Dakshineswar), Narendranath asked him the question which he had asked others often before: "Sir, have you seen God?" "Yes, answered Sri Ramakrishna, "I see Him just as I see you here, only I see Him in a much intenser sense. God can be realised; one can see and talk to Him as I am doing with you. But who cares to do so? People shed torrents of tears for their wife and children for wealth and property, but who does so for the sake of God? If one weeps sincerely for Him. He surely manifests Himself."</p>
<p>This startling reply impressed Narendranath at once. For the first time he had found a man who could say that he had seen God, and recognised that religion was a reality to be felt. As he listened, he could not but believe that Sri Ramakrishna spoke from the depths of his own realisations</p>
<p><strong>Compiled and Edited by Swami Gambhirananada</strong> The Apostles of Sri Ramakrishna Advaita Ashrama; Mayavati; June 1995</p>
<p>About Swami Vivekananda</p>
