<h1>Last year in India</h1>
<h2>&nbsp;</h2>
<p>Immediately after arrival in Bombay, he left for Calcutta, and reached Belur Math late in the evening of 9th December, 1900, without any previous intimation. The gates of the monastery were closed for the night. Hearing the dinner bell, in his eagerness to join the monks at their meal, he scaled the gate. There was great rejoining over the hero's home-coming.</p>
<h3>The tree under his room, where he received visitors</h3>
<p>Now the Swami tried to lead a carefree life at the monastery, surrounded by his pets: the dog Bagha, the she-goat Hansi, an antelope, a stork, several cows and sheep and ducks and geese, and a kid which he named Matru. He used to run and play with Matru on the grounds, sometimes clad in his loin-cloth ; or he would supervise the cooking arrangement ; or be with the monks singing devotional songs.</p>
<p>Sometimes he would be seen imparting spiritual instruction to the visitors, at other times engaged in serious study in his room or explaining to the members of the Math the intricate passages of the scriptures and unfolding to them his scheme of future work.</p>
<h3>Swamiji's room overlooking the Ganges (view from the river)</h3>
<p>He freed himself entirely from all formal duties by executing a deed of trust in favour of his brother disciples, investing in them all the properties, including the Belur Math so far held in his name. Brahmananda was elected President. Still he kept a careful watch on the life in the monastery, in spite of his physical suffering, and he was obeyed unquestioningly by all including the President. He looked to every detail - cleanliness, meals, study, meditation, work. He drew up a weekly time-table and saw to it that it was scrupulously followed. The classes on the Vedas and the Puranas were held daily, he himself conducting them when his health permitted.</p>
<h3>Inside his room - where he studied</h3>
<p>The bell sounded at fixed hours for meals, study, discussion, and meditation. About three months before his death, he made it a rule that at four o'clock in the morning a handbell should be rung from room to room to awaken the monks. Within half an hour all were to gather in the chapel for meditation. He was always there before them. He got up at three and went to the chapel, where he meditated for more than two hours. As he got up, he used to chant softly "Shiva!" Shiva!". His presence in the chapel created an intense spiritual atmosphere. Swami Brahmananda used to say: "Ah! one at once becomes absorbed if one sits for meditation in the company of Naren. I do not feel this when I sit alone."</p>
<p><strong>Compiled and Edited by Swami Gambhirananada</strong> The Apostles of Sri Ramakrishna Advaita Ashrama; Mayavati; June 1995</p>
<p>About Swami Vivekananda</p>
