<h1>Next few years</h1>
<h2>&nbsp;</h2>
<h3>Master and Disciple</h3>
<p>The second time Narendranath went to Dakshineswar, a month later. Sri Ramakrishna was alone, sitting on his bedstead. As soon as he saw Narendranath, he received him cordially and asked him to sit near himself on the bed. In a moment, overcome with emotion, the Master drew closer to him. Muttering something to him, and with eyes fixed on the young aspirant, he touched him with his right his foot. The magic touch produced a strange experience in Narendranath. With his eyes open, he saw the walls and everything in the room, nay, the whole universe and himself within it, whirling and vanishing into an all-encompassing void. He was frightened as he thought he might be on the verge of death; and cried out: "What are you doing to me? I have my parents at home." Sri Ramakrishna laughed aloud at this, and stroking Narendranath chest said: "All right, let us leave it there for the present. Everything will come in time." Surprisingly, as soon as he uttered these words, Narendranath became his old self again. Sri Ramakrishna, too, was quite normal in his behaviour towards him after the incident, and treated him kindly and with great affection.</p>
<p>Drawn by this kindness and, even more, by the need to fathom the mystery, Narendranath went to Dakshineswar for a third time, probably a week later. He was determined not to allow the previous experience to repeat itself, and was fully on his guard. But with all his critical faculties alert, he fared no better. Sri Ramakrishna took him to the adjacent garden belonging to Jadunath Mallik. After a stroll, they sat down in the parlour. Soon, Sri Ramakrishna fell into a spiritual trance and touched Narendranath. Despite his precautions Narendranath was totally over-whelmed adn he lost all outward consciousness. When he regained consciousness, he found Sri Ramakrishna stroking his chest.</p>
<p>Referring to his incident, Sri Ramakrishna said later on: "I put several questions to him while he was in that state. I asked him about his antecedents, and where he lived, his mission in this world and the duration of his mortal life. He gave fitting answers after diving deep into himself. The answers only confirmed what I had seen and inferred about him, These things shall remain a secret, but I came to know that he was a sage who had attained perfection, a past master in meditation, and the day he know his real nature, he will give up the body by an act of will, through Yoga."</p>
<p>Of all the disciples of Sri Ramakrishna, Narendranath alone doubted the Master and critised any of his teachings that appeared irrational.</p>
<p>Firmly poised as he was in the knowledge of the highest truth, Sri Ramakrishna, however, did not upset the intellectual outbursts of Narendranath. He rose equal to the occasion. He never asked Narendranath to abandon his reason. On the other hand, he enjoyed his criticisms, and even encouraged them. He told him: "Test me as the money changers test their coins. You must not accept me until you have tested me thoroughly."</p>
<p>Narendranath was bitterly against the doctrine of Advaita Vedanta which Sri Ramakrishna was eager to explain to him. The Advaita idea of the identity of the individual soul and the Supreme Self appeared to him as bizarre and blasphemous. Sri Ramakrishna tried his best to bring home to the disciple the truth of Advaita by reason and argument, but without success. One day after a trying discussion, he found Narendranath speaking about the doctrine disparagingly to a friend and in a light vein. Sri Ramakrishna, in a semi-conscious mood, approached him and just touched him, and immediately a wonderful change came over Narendranath. He was filled with the consciousness that everything around him was God. The impression persisted even when he reached home, at the end of the day. He did not relish his food. He ate too much or too little, to the consternation of his mother. He felt that the food, the materials, the server and he himself were all God. In the street, he did not feel like moving out of way of the swiftly, moving cabs, thinking they were God Himself. In the public park, he struck his head against the railing to see if they were real. This feeling lasted for many days. Henceforth he could not deny the truth of Advaita.</p>
<p>In 1884, Vishwanath Datta (Narendranath's father) suddenly passed away, plunging the whole family into grief and poverty. He was the only earning member of the family, and being of a prodigal nature, he spent lavishly and left the family in debt.</p>
<p>Everywhere the door was slammed in his (Vivekananda's) face. Friends turned into enemies in an instant. Creditors began knocking at the door. Temptations came. Two rich women made proposals to him to end his poverty, and he turned them down with scorn. Often he went without food so that others at home might have a better share. He was face to face with realities and the world appeared to him to be the creation of a devil.</p>
<p>Nevertheless, the protégé of Sri Ramakrishna did not lose his faith in God and divine mercy. Every morning, taking His name he got up and went in search of a job. One day his devout mother overheard him and said bitterly: "Hush, you fool, you have been crying yourself hoarse for God from your childhood. What has He done for you?" Narendranath was stung to the quick, and began doubting the existence of God.</p>
<p>One evening, after a whole day's fast and exposure to rain, Narendranath was returning home with tired limbs and a jaded mind. Overpowered with exhaustion, he sat down on the outer plinth of a roadside house in a dazed condition. Various thoughts crowded into his mind. He was too weak to drive them off and concentrate on any particular thing. Suddenly he felt that, by some divine power, the coverings of his soul were being removed one after another. His doubts regarding the coexistence of divine justice and mercy and the presence of misery in the creation of a benign providence were automatically sloved. He felt completely refreshed and full of mental peace. He decided to become a monk, renouncing the world. He even fixed a date for it. Sri Ramakrishna came to Calcutta that day. Narendranath went to have his blessings, and accompanied the Master to Dakshineswar. There, in a state of spiritual trance, Sri Ramakrishna began to sing a touching song which brought tears to the eyes of both. The meaning of the song was very clear, for it revealed that the Master had known the disciple's decision even without being told of it. But Sri Ramakrishna persuaded Narendranath to stay in the world as long as he himself lived.</p>
<p>Thus, with infinite patience, Sri Ramakrishna calmed the rebellious spirit of Narendranath and led him from doubt to certainty and from anguish of mind to spiritual bliss. More than Sri Ramakrishna's spiritual guidance and support, it was his love for him that bound Narendranath to him for ever. Narendranath, too, in turn reciprocated in full measure the love and trust of the Master.</p>
<p>An incident which had some bearing on the future work of Narendranath may be mentioned here. Once, Sri Ramakrishna was expatiating on the triple precept of the Vaishnavas, namely, relish for the name of God, compassion for all creatures, and service to the Lord's devotees. When he came to compassion for all creatures, he said in a semiconscious state, as if speaking to himself: "Thou fool! An insignificant worm crawling on earth, who are thou to show compassion? No, it is not compassion for others, but services to man, seeing in him the veritable manifestation of God." Narendranath, who was near by, drew from these simple words, which went unnoticed by others present there, a world of meaning, and vowed to proclaim to the whole world the grand truth which he had discovered in them. It was then that he conceived his philosophy of practical Vedanta.</p>
<p>In the middle of 1885. Sri Ramakrishna developed cancer in the throat. For better treatment he was taken to a rented garden house at Cossipore, a northern suburb of Calcutta. The young disciples, under the leadership of Narendranath, took charge of nursing the Master.</p>
<p>At Cossipore also, as earlier at Dakshineswar, Sri Ramakrishna impressed on the other disciples the high plane of spirituality to which Narendranath belonged, and the mission he was born to fulfill. He often talked with Narendranath privately about the orders of monks he was to organise, with the brother disciples as the nucleus. Narendranath was thus chosen and trained as the future leader of a spiritual regeneration.<br /> Having finished his immediate task and being assured of a glorious future for the new movement, Sri Ramakrishna passed away on 16th August 1886.</p> 
<p><strong>Compiled and Edited by Swami Gambhirananada</strong> The Apostles of Sri Ramakrishna Advaita Ashrama; Mayavati; June 1995</p>
<p>About Swami Vivekananda</p>
