<h1>Return of the Hero</h1>
<h2>&nbsp;</h2>
<p>Though the Swami was completely absorbed in his work in the West, he never forgot about his original mission. He was constantly in correspondence with his disciples in Madras and elsewhere, guiding, instructing, and encouraging them to push on with the work in India. In his immortal letters, detailed instructions were given about organizing the work. To quote only a few of his inspiring words: "Work hard, be steady, and have faith in the Lord. . . . Keep the motto before you - 'Elevation of the masses without injuring their religion'. . . the fate of a nation does not depend upon the number of husbands their widows get, but upon the condition of the masses. Can you raise them? Can you give them back their lost individuality? . . . This is to be done and we will do it. You are all born to do it. Have faith in yourselves, great convictions are the mothers of great deeds." (Complete Works, 1963, V. 29-30).</p>
<h3>Return of the Hero</h3>
<p>In the middle of November 1896, he suddenly decided that he must go back to India. So he asked Mrs. Servier, after a class talk, to book their berths for India from Naples by the earliest steamer available. On 16th December the Swami left London with the Serviers.</p>
<p>At Naples, Mr. Goodwin joined the party, and they arrived in Colombo on 15th January 1897.</p>
<p>The news of the swami's return had already reached India. He was no longer the unknown, wandering Sannyasin. The great work he had done for India in the west had become known throughout India. From Colombo to Madras, in all the important cities, committees consisting of all sections of the society had been formed to accord him a fitting reception.</p>
<p>All along the route of his tour, specially in Jaffna and Kumbakonam, he gave inspiring lectures, reminding the people of the glory of India's past and exhorting them to apply themselves to the task of raising her to her ancient splendour. But it was in Madras that he gave full expression to his ideas. On the third day after his arrival, a public address of welcome was presented to him at the Victoria Hall, but it was too small to contain the large gathering. The Swami at the insistent demand of the enthusiastic public waiting outside, spoke to them in the open from the top of a coach in "the Gita fashion", urging them to maintain their enthusiasm and utilize it for the service of India. During his stay in Madras the Swami gave five public lectures, the subjects selected being "My Plan of Campaign", The Sages of India", Vedanta in Its Relation to Practical Life", The Work before Us", and "The Future of India". In these, the Swami addressed the whole of India, and here one finds his message to India expressed in the most inspiring Languages.</p>
<p>Let us listen to a few of his soul-stirring words: "I see that each nation, like each individual, has one theme in this life, which is its centre, the principal note round which every other note comes to form the harmony, in one nation political power is its vitality, as in England, artistic life in another, and so on. In India, religious life forms the centre, the keynote of the whole music of national life. …. Therefore, if you succeed in the attempt to throw off your religion and take up either politics, or society, or any other things as your centre, as the vitality of your national life, the results will be that you will become extinct.</p>
<p>Every man has to make his own choice ; so has every nation. We made our choice ages ago and we must abide by it. And, after all, it is not such a bad choice. It is such a bad choice in this world to think not of matter but of spirit, not of man but of God?</p>
<p><strong>Compiled and Edited by Swami Gambhirananada</strong> The Apostles of Sri Ramakrishna Advaita Ashrama; Mayavati; June 1995</p>
<p>About Swami Vivekananda</p>
