<h1>Swamiji's addresses at the Parliament</h1>
<h2>&nbsp;</h2>
<ul>
	<li>At the World's Parliament of Religions, Chicago 11th September, 1893</li>
	<li>Why we disagree, 15th September, 1893</li>
	<li>Address at the final session, 27th September, 1893</li>
</ul>
<h3>Sister and Brothers of America</h3>
<h3>At Chicago</h3>
<p>It fills my heart with joy unspeakable to rise in response to the warm and cordial welcome which you have given us. I thank you in the name of the most ancient order of monks in the world; I thank you in the name of the mother of religions; I thank you in the name of millions and millions of Hindu people of all classes and sects.</p>
<p>My thanks, also, to some of the speakers on this platform who, referring to the delegates from Orient, have told you that these men from far-off nations may well claim the honor of bearing to different lands the idea of toleration. I am proud to belong to a religion which has taught the world both tolerance and universal acceptance. We believe not only in universal toleration, but we accept all religions as true. I am proud to belong to a nation which has sheltered the persecuted and the refugees of all religions and nations of the earth. I am proud to tell you that we have gathered in our bosom the purest remnant of the Israelites, who came to Southern India and took refuge with us in the very year in which their holy temple was shattered to pieces by Roman tyranny. I am proud to belong to the religion which has sheltered and is still fostering the remnant of the grand Zoroastrian nation. I will quote to you, brethren, a few lines from a hymn which I remember to have repeated from my earliest boyhood, which is every day repeated by millions of human beings: "As the different streams having their sources in different places all mingle their water in the sea, sources in different tendencies, various though they appear, crooked or straight, all lead to Thee."</p>
<p>The present convention, which is one of the most august assemblies ever held, is in itself a vindication, a declaration to the world of wonderful doctrine preached in the Gita: "Whosoever comes to Me, through whatsoever form, I reach him; all men are struggling through paths which in the end lead to me." Sectarianism, bigotry, and its horrible descendant, fanaticism, have long possessed this beautiful earth. They have filled the earth with violence, drenched it often and often with human blood, destroyed civilization and sent whole nations to despair. Had it not been for these horrible demons, human society would be far more advanced than it is now. But their time is come; and I fervently hope that the bell that tolled this morning in honor of this convention may be the death-knell of all fanaticism, of all persecutions with the sword or with the pen, and of all uncharitable feelings between persons wending their way to the same goal.</p>
<h3>Why We Disagree, 15th September, 1893</h3>
<h3>The Orator by Divine Right Chicago October 1893</h3>
<p>I will tell you a little story. You have heard the eloquent speaker who has just finished say, "Let us cease from abusing each other", and he was very sorry that there should be always so much variance.</p>
<p>But I think I should tell you a story which would illustrate the cause of this variance. A frog lived in a well. It had lived there for a long time. It was born there and brought up there, and yet was a little, small frog. Of course the evolutionists were not there then to tell us whether the frog lost its eyes or not, but, for our story's sake, we must take it for granted that it had its eyes, and that it every day cleansed the water of all the worms and bacilli that lived in it with an energy that would do credit to our modern bacteriologists. In this way it went on and became a little sleek and fat. Well, one day another frog that lived in the sea came and fell into the well. "Where are you from?" "I am from the sea." "The sea! How big is that? Is it as big as my well?" and he took a leap from one side of the well to the other. "My friend", said the frog of the sea, "how do you compare the sea with your little well?" Then the frog took another leap and asked, "Is your sea so big?" "What nonsense you speak, to compare the sea with your well" "Well, then," said the frog of the well, "nothing can be bigger than my well; there can be nothing bigger than this; this fellow is a liar, so turn him out."</p>
<p>That has been the difficulty all the while.</p>
<p>I am a Hindu. I am sitting in my own little well and thinking that the whole world is my little well. The Christian sits in his little well and thinks the whole world is his well. The Mohammedan sits in his little well and thinks that is the whole world. I have to thank you America for the great attempt you are making to break down the barriers of this little world of ours, and hope that, in future, the Lord will help you to accomplish your purpose.</p>
<h3>Address at the final session, 27th September, 1893</h3>
<p>The World's Parliament of Religions has become an accomplished fact, and the merciful Father has helped those who labored to bring it into existence, and crowned with success their most unselfish labour.</p>
<h3>From the Chicago archives (1893)</h3>
<p>My thanks to those noble souls whose large hearts and love of truth first dreamed this unfearful dream and then realized it. My thanks to the shower of liberal sentiments that has overflowed this platform. My thanks to this enlightened audience for their uniform kindness to me and for their appreciation of every thought that tends to smooth the friction of religions. A few jarring notes were heard from time to time in this harmony. My special thanks to them, for they have, by their striking contrast, made general harmony the sweeter.</p>
<p>Much has been said of the common ground of religious unity. I am not going just now to venture my own theory. But if anyone here hopes that this unity will come by the triumph of anyone of the religions and the destruction of others, to him I say, "Brother, yours is an impossible hope." Do I wish that the Christian would become Hindu? God forbid. Do I wish that the Hindu or Buddhist would become Christian? God forbid.</p>
<p>The seed is put in the ground, and earth and air and water are placed around it. Does the seed become the earth, or the air, or the water? No. It becomes a plant, it develops after the law of its own growth, assimilates the air, the earth, and the water, converts them into plant substance, and grows into a plant.</p>
<p>Similar is the case with religion. The Christian is not to become a Hindu or a Buddhist, not a Hindu or a Buddhist to become a Christian. But each must assimilate the spirit of the others and yet preserve his individuality and grow according to his own law of growth.</p>
<p>If the Parliament of Religions has shown anything to the world it is this: It has proved to the world that holiness, purity and charity are not the exclusive possessions of any church in the world, and that every system has produced men and women of the most exalted character. In the face of this evidence, if anybody dreams of the exclusive survival of his own religion and the destruction of the others, I pity him from the bottom of my heart, and point out to him that upon the banner of every religion will soon be written, in spite of resistance: "Help and not Fight", "Assimilation and not Destruction," "Harmony and Peace and not Dissension."</p>
<p>About Swami Vivekananda</p>
