<h1>The Baranagore days</h1>
<h2>&nbsp;</h2>
<p>After the death of the Master. One of the lay disciples of Shri Ramakrishna offered to contribute towards the maintenance of a monastery where the young disciples of the Master could stay and continue their spiritual and devotional exercises, and where the householder disciples might now and then go for peace and solace. Accordingly, an old dilapidated house was rented at the Baranagore, and two of the monastic disciples went to live there. Narendranath who was busy conducting a law suit pending at the court, used to spend the night at the monastery. He exhorted the others to join the brotherhood.</p>
<h3>At Baranagore - after the passing away of the Master</h3>
<p>Lest this devotion should become dammed up within the narrow limits of a creed or cult, the leader forced them to study the thought of the world outside. He himself instructed them in western and eastern philosophy, comparative religion, theology, history, sociology, literature, art, and science. He read out to them the great books of human thought, explained to them the evolution of the universal mind, discussed with them the problems of religion and philosophy, and led them indefatigably towards the wide horizons of the boundless truth which surpassed all limits of schools and races, and embraced and unified all particulars truths. In the light of the teachings of Shri Ramakrishna, he reconciled the apparent contradictions between the various systems.</p>
<p><strong>The wandering monk</strong></p>
<h3>The wandering - nameless monk - befriending princes and commoners</h3>
<p>Between the closing of 1888, when Narendranath first left on his temporary excursions, and the year 1891, when he parted from his brethren alone and as an unknown beggar, "to be swallowed up in the immensity of India", there came over him a remarkable change in outlook. When he first left in 1888, it was mainly to fulfill the natural desire of an Indian monk for a life of solitude. But when he left the monastery in 1891, it was to fulfill a great destiny. By then he had realized that his was not to be the life of an ordinary recluse struggling for personal salvation. Many times he had tried it: he had entered the deepest of Himalayan forests to lose himself in the silent meditation of the absolute. Every time he had failed. Something or other brought him back from the depths of meditation to the midst of the suffering masses, beset with a thousand and one miseries. The sickness of a brother monk, or the death of a devotee, or the poverty at the Baranagore monastery, was enough to disturb him. More than all, the fever of the age, the misery of the time, and the mute appeal issuing from the millions in oppressed and downtrodden Indian pained his heart.</p>
<h3>Seeking answers for India and the world</h3>
<p>He lived in anguish during that period, in a seething cauldron as it were, and carried within himself a soul on fire whose embers took years to cool down. As he moved from place to place in the north, and later on in the south, studying closely the life of the people in all strata of society, he was deeply moved. He wept to see the stagnant life of the Indian masses crushed down by ignorance and poverty, and the spell of materialistic ideas among the educated who blindly imitated the glamour of the West but who never felt that they were the cause of India's degeneration and downfall. Spirituality was at a low discount in the very land of its birth. The picture of ancient India, once the envy of the world, came before his eyes vividly in all its grandeur and glory. The contrast was unbearable. Things should not be allowed to drift in this way. He visualized that India must become dynamic in all spheres of human activity and effect the spiritual conquest of the world, and he felt that he was the instrument chosen by the Lord to do it.</p>
<p><strong>Compiled and Edited by Swami Gambhirananada</strong> The Apostles of Sri Ramakrishna Advaita Ashrama; Mayavati; June 1995</p>
<p>About Swami Vivekananda</p>
