<h1>The Parliament of Religions</h1>
<h2>&nbsp;</h2>
<h3>The Parliament of Religions</h3>
<p>At Porbandar, where he arrived after visiting Verawal and Somnath (Prabhas), he stayed for eleven months, and helped the Dewan of the place, Pandit Shankar Pandurang, in translating the Vedas. He completed his study of the Mahabhashya, and learnt French at the instance of the Dewan, who suggested to him to go to the West, where his ideas were likely to be better appreciated. Hearing about the Parliament of Religions to be held at Chicago he expressed to his host at Porbander his desire to attend it.</p>
<p>The Swami found himself the guest of the Maharaja of Mysore, Chamaraja Wadiar. In his talk with the Maharaja, he unburdened the heavy load he was, as it were, carrying on his head, and expressed his intention of going to the West to get funds to ameliorate the material condition of India. The Maharaja offered to bear the expenses.</p>
<p>While arrangements were being made for sailing, a sudden invitation came from the Maharaja of Khetri to go to his place, with the assurance that he would do everything for the trip. The Swami agreed to this. With the Maharaja he went to Jaipur, and from there he left for Bombay alone. On the way to Bombay he halted for a night at the house of a railway employee, one of his hosts during his wandering days. At Mt. Abu he met Swamis Brahmananda and Turiyananda, to whom he said with great feeling: Ï travelled all over India. But, alas, it was agony to me, brothers, to see the terrible poverty of the masses, and I could not restrain my tears. It is now my firm conviction that to preach religion to them without trying to remove their poverty and suffering is futile. It is for this reason-to find means for the salvation of the poor of India-that I am going to America."</p>
<p>The first session of the Parliament was held on Monday, 11th September 1893, in the spacious hall of the Art Palace; and its huge galleries were packed with nearly 7,000 people-men and women representing the best culture of the country. Representatives of all organized religions-Hinduism, Jainism Buddhism, Christianity, Confucianism, Mohammedanism, and Mazdaism-were there, and amongst them was Swami Vivekananda, who represented no particular sect. the Swami represented nothing and yet everything. There was a grand procession of delegates. Cardinal Gibbons, the highest prelate of the Roman Catholic Church in the U.S.A., opened the meeting with a prayer and, after that, Dr. Barrows, the Chairman, introduced the delegates one by one. All of them, except Swami Vivekananda, read prepared for the first time, and his heart was fluttering and his tongue dried up. He was so nervous that he did not speak in the morning session. He went on postponing the summons from the chair.</p>
<h3>At the Parliament of Religions</h3>
<p>In the end, when he could no longer put off his turn, he stepped up to the rostrum and, in his mind, bowing down to Saraswati Devi, began to speak. No sooner had he addressed the assembly "Sisters and Brothers of America" than there was deafening applause lasting for full two minutes. The audience rose as one man to express heartfelt appreciation for the warm feelings which those five simple words conveyed to them. Others addressed them in the set way, but the Swami touched the deepest cord of their hearts by discarding the formality and stressing the kinship of humanity with such sincerity. After the applause had subsided, the Swami made a brief speech.</p>
<p>The Swami, however, did not take this as a personal triumph. Although he had become famous overnight, and the doors of the rich were open to him, he wept over his victory, remembering his people at home, sunk in poverty and ignorance, for whose sake he had come to America.</p>
<p><strong>Compiled and Edited by Swami Gambhirananada</strong> The Apostles of Sri Ramakrishna Advaita Ashrama; Mayavati; June 1995</p>
<p>About Swami Vivekananda</p>
