<h1>Work in India</h1>
<h2>&nbsp;</h2>
<h3>Udbodhan - the only Bengali mouthpiece of Ramakrishna Math and Mission, started by Swami Vivekananda in January 1899</h3>
<p>For the purpose of establishing his work on a firm basis, the Swami summoned all the monastic and lay disciples of Shri Ramakrishna to a meeting at Balaram Bose's house on 1st May 1897. He told them that he has conclusion that without an organization nothing great and permanent could be achieved, and proposed that an association be formed in the name of the Master know as the Ramakrishna Mission. The aims and ideals of the Mission as propounded by the Swami were purely spiritual and humanitarian. The Mission had nothing to do with politics. Suitable resolutions were passed to this effects and the Ramakrishna Mission came into being. The Swami himself became the General President, Swami Yogananda the Vice-President, and Swami Brahmananda the President of the Calcutta centre.</p>
<h3>The office of "Udbodhan"</h3>
<p>To fulfill the Swami's cherished dream of having a permanent monastery on the Ganga, plot of land was secured at Belur, near Calcutta, early in 1898, and the Math was removed to Nilambar Mukherjee's garden house at Belur.</p>
<p>His main concern, however, was the training of the young Sannyasins and Brahmacharins, who were to carry on his work in the future. He encouraged them to develop an all-round personality, himself setting the example. He arranged study classes them: "You will go to hell if you seek your own salvation. Seek the salvation of others if you want to reach the Highest." You must try to combine in your life immense idealism with immense practicality. You must be prepared to go into deep meditation now, and the next moment you must be ready to go and cultivate the fields. You must be prepared to explain the intricacies of the scriptures now, and the next moment to go and sell the produce of the fields in the market…… The true man is he who is strong as strength itself and yet possesses a woman's heart."</p>
<p><strong>Compiled and Edited by Swami Gambhirananada</strong> The Apostles of Sri Ramakrishna Advaita Ashrama; Mayavati; June 1995</p>
<p>About Swami Vivekananda</p>
