<h1>Work in America</h1>
<h2>&nbsp;</h2>
<p>In order to further the cause of India and to free himself from obligation to his friends, he accepted the offer of a lecture bureau for a lecture tour of America. He thought that would help him also in spreading his ideas. The tour took him round the large cities in the Eastern and Mid-Western States. Everywhere, people flocked to hear him. His speeches, delivered extempore, were mostly devoted to the exposition of religion and philosophy as preached and practiced by the Hindus through the centuries. He also explained to the America audience the Hindus manners, customs, and religious practices, removing some of the misconceptions spread through the monstrous and fantastic stories told by the Christian missionaries.</p>
<h3>The Hindoo Monk (as he was known then! - a newspaper picture)</h3>
<p>The Swami also spoke with great reverence on Christ and his teachings and the valuable contribution of the West to the culture and civilization of the world. He did not hide his admiration for the tremendous progress the West had made in the fields of industry and economics, as well as for the western democratic social systems with equal opportunity for everyone. While he was never sparing in his praise of the good side of western civilization, the hollowness of the western society- the tears behind the peal of laughter-became more and more apparent to him as he moved from city to city. He was mercilessly critical of the defects in European culture-the signs of brutality, inhumanity, pettiness, arrogance, and ignorance of other cultures-as he was severe in his criticism of the defects of Indian social customs like untouchability and other allied evils during his lectures from Colombo to Almora after his return from the West in 1897.</p>
<p>Thus the Swami's western work took him gradually beyond his original plan, which was just to raise money for the uplift of the Indian masses. He realized that his services could not be confined within narrow limits. He wrote to his disciples who were urging him to return to India: "I have helped you all as I could. You must now help yourselves. What country has any special claim on me? Am I a nation's slave? I do not care whether they are Hindus, or Mohammedans, or Christians, but those that love the Lord will always command my service." He gave away most of his earnings through lectures to the charitable institutions there in American and asked his friends to do the same. He wholeheartedly devoted himself to the service of the West.</p>
<p>This attitude, however, was no mere volte face. It arose from the fact that he had become conscious of the full significance of his life's work. His mission was to the whole world, not to India only. He realized that his task was to preach the fundamental universal principles of religion, and to preach them to all countries. Later he was to assure India that only if she clung to those universal principles, which were her birthright, would her poverty and other problems be solved. To these universal principles he gave the name "Vedanta". As Miss Marie Burke writes in Swami Vivekananda in America: "Never before had it been broadened into a philosophy and religion which included every faith of the world and every noble effort of man-reconciling spirituality and material advancement, faith and reason, science and mysticism, work and contemplation, service to man and absorption in God. Never before had it been conceived as the one universal religion, by accepting the principles of which the follower of any or no creed could continue along his own path and at the same time be able to identify himself with every other creed and aspect of religion.</p>
<p>"The Herculean task of teaching Vedanta in a foreign land had completely worn him out; he needed rest badly.</p>
<h3>The Thousand Island Park - where he rested</h3>
<p>Thence he proceeded to Thousand Island Park on the St. Lawrence where, at the earnest request of a few students, who were ready to put aside all other interests to study Vedanta, he agreed to hold classes for them.</p>
<p>There, under ideal surroundings, he taught those intimate students. The subjects discussed in that heavenly atmosphere surcharged with his spirituality were many. The Swami expounded to them such precious texts as the Bhagavad-Gita and the Narada-Bhakti-Sutras, with his mind always absorbed in Brahman. He himself said later that he was at his best at Thousand Island Park. One of the students records: "Of the wonderful weeks that followed, it is difficult to write. Only if one's mind were lifted to that high state of consciousness in which we lived for the time, could one hope to recapture the experience. We were filled with joy. . . . On the wings of inspiration, he carried us to the height which was his natural abode. … His first overwhelming desire was to show us the path of Mukti, to set us free. … His second object … was to train this group to carry on the work in America." There he reached one of his loftiest heights ;the students saw ideas unfold and flower. He sought to awaken the heroic energy of the souls placed in his hands. He said: "If I could only set you free with a touch!" And how many were helped to freedom during his lifetime; Besides, the number of those who are being inspired to divinity by his immortal message is on the increase as time rolls on.</p>
<p>A concrete result of his New York work was the establishment of a Vedanta Society there, under the presidentship of Mr. Francis H. Leggett.</p>
<p>The Swami had seen by now the best and the worst of both the East and the West. He was now convinced that each had something to learn from the other. Ï believe that the Hindu faith has developed the spiritual at the expense of the material," he said, "and I think that in the West the contrary is true. By uniting the materialism of the West with the spiritualism of the East, I believe much can be accomplished." In Detroit, he said: "May not one combine the energy of the lion and the gentleness of the lamb? Perhaps, the future holds the conjunction of the East and the West, a combination which would be productive of marvelous results." The problem was how to harmonise everything without sacrificing anything. He had in his mind the plan of bringing his brother disciples to teach and preach Vedanta in America, and taking some of his American and English disciples to teach science, industry, economics, applied sociology, organization, and co-operation in India.</p>
<p>That, however, would not go far unless there was a complete and thorough reorganization of the great religious and philosophical thought of India on a sound national and universal basis. Then alone could Indian thought recover its dynamic drive and progressive power to advance and spiritualise the west. For this purpose, he seriously thought of writing a book. He revealed this idea of his to Alasinga, his disciple, thus: "Now, I will tell you my discovery. All of religion is contained in Vedanta, that is, the three stages of the Vedanta philosophy-the Dvaita, Vishishtadvaita, and Advaita; one comes after the other. These are the three stages of spiritual growth in man. Each one is necessary. This is the essential of religion. The Vedanta applied to the various ethnic customs and creeds of India is Hinduism. The first stage, Dvaita, applied to the idea of ethnic groups of Europe is Christianity; as applied to the Semitic groups, Mohammedanism. The Advaita as applied in its Yoga perception form is Buddhism, etc. now by religion is meant Vedanta. The application must vary according to the different needs, surroundings, and other circumstances of different nations.</p>
<p><strong>Compiled and Edited by Swami Gambhirananada</strong> The Apostles of Sri Ramakrishna Advaita Ashrama; Mayavati; June 1995</p>
<p>About Swami Vivekananda</p>
