<h1>What does the Ramakrishna Mission stand for?</h1>
<h2>&nbsp;</h2>
<h3>The Emblem</h3>
<p><i>Designed and explained by Swami Vivekananda</i></p>
<p>The wavy waters in the picture are symbolic of work, and the lotus of devotion, and the rising sun of knowledge. The encircling serpent is indicative of yoga and the awakened power dormant in us, while the swan in the picture stands for God. Therefore, the idea of the picture is that by the union of work, knowledge, devotion, and yoga, the vision of God is obtained.</p>
<h3>The Ramakrishna Movement</h3>
<p><i>(Excerpts from article by Swami Lokeshwarananda)</i></p>
<p>When it started in 1897, the Ramakrishna Order consisted of a dozen monks or so and had practically no assets. Even at its present stature, in numbers of centres and the monks it has, it is small compared with the Christian organizations, but it is a name that commands respect all over India and even outside.</p>
<p>These monks try to make 'a Hindu a better Hindu, a Muslim a better Muslim, a Christian a better Christian' and so on. In other words, they ask people to go to the root of religion, which is trying to reach God somehow or other and not merely talking about Him. They quote different prophets and different scriptures to show how in essence they preach the same thing. Their language differs, but their purport is the same. They do not want to replace any system but want to draw attention to the fact that there is much in common between one system and another. In all matters of religion, their approach is one of respect and understanding. Because of this approach, they feel as much at home among non-Hindus as among Hindus. Because of this approach, non-Hindus also feel at home in their company; as a matter of fact they like these monks and often invite them to their services.</p>
<p>Today the Ramakrishna Movement has become a great power for peace and happiness in this country as well as outside. In India where different religious sects and communities live, the idea of tolerance and brotherly feelings towards each other has great relevance. Another factor which contributes much to its popularity is the rational approach it brings to bear upon every vital problem of life. People who are influenced by Ramakrishna believe religion to be a kind of science open to study and investigation. They do not agree that religious truths have to be accepted on trust; they rather declare that nothing need be accepted as final unless it has been tested and found true. Experience, personal and immediate, is the only acceptable proof of religion.</p>
<p>The fact that the Movement lays great stress on selfless service as a means of God-realization also attracts many people. The service it gives is open to all, irrespective of caste or creed or language.</p>
<p>As time passes, the Ramakrishna Movement is growing from strength to strength. People all over the country want the Mission to open more branch centres - schools, colleges, hospitals, orphanages, etc., for they know that the quality of service they will get from the Mission will be better than what they may get elsewhere. Their requests are almost always accompanied by offers of money, land, and buildings, but the Mission proceeds cautiously and avoids proliferation unless there is a compelling reason in its favour. Apart from the fact that it suffers from shortage of manpower, it prefers that people themselves come forward to start such institutions, imbued with the spirit of selfless service. Happily, the present trend clearly shows that this spirit is fast spreading.</p>
<p>As the Movement spreads the attitude of the common people towards religion is also changing. Previously, religion was equated with rituals, but now people realize that religion is essentially a science of 'being and becoming', something that concerns man's inner nature. The habit of prayer is good but if this is not accompanied b a corresponding improvement in one's nature, it is not worth much. Another change that is noticeable today is respect for religions other than one's own. There was once much arrogance in the attitude of people towards the religions of others, but there is now humility and a spirit of enquiry if not also reverence.</p>
<p>Ruskin once said, 'An idea is more powerful than an army'. There must be much truth in this, else it is difficult to explain the influence Ramakrishna and the Order of monks bearing his name have had over people all over the world. The strength of the Ramakrishna Movement is not in money, men or organization but in the ideas it tries to present. These ideas are fast spreading, and wherever they are spreading they are producing a great impact. Silently but inevitably, they are changing the minds of the people who come under their influence. They act like a catalytic agent transforming their personalities.</p>
<p><strong>The Ramakrishna Movement;</strong> <i>The Ramakrishna Mission Institute of Culture; Calcutta; July 2000</i></p>



